apiVersion: v1
kind: Secret
metadata:
  name: alertmanager
stringData:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_from: MAILFROM_SED
      smtp_require_tls: False
      smtp_smarthost: MAILRELAY_SED:25
    inhibit_rules:
    - source_match_re:
        internal: workinghours
      target_match:
        job: .+
    receivers:
    - name: deadmansswitch
    - name: default
      email_configs:
      - from: MAILFROM_SED
        send_resolved: true
        to: MAILTO_SED
    route:
      group_by:
      - job
      group_interval: 5m
      group_wait: 30s
      receiver: default
      repeat_interval: 12h
      routes:
      - match:
          alertname: DeadMansSwitch
        receiver: deadmansswitch
        repeat_interval: 5m
      - match:
          severity: warning
        receiver: default
        repeat_interval: 6h
      - match:
          severity: critical
        receiver: default
        repeat_interval: 3h
type: Opaque
