apiVersion: v1
kind: Secret
metadata:
  name: alertmanager
stringData:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    inhibit_rules:
    - source_match_re:
        internal: workinghours
      target_match:
        job: .+
    receivers:
    - name: deadmansswitch
    - name: default
      slack_configs:
      - api_url: SLACK_URL_SED
        channel: #monitoring
        send_resolved: true
    route:
      group_by:
      - job
      group_interval: 5m
      group_wait: 30s
      receiver: default
      repeat_interval: 12h
      routes:
      - match:
          alertname: DeadMansSwitch
        receiver: deadmansswitch
        repeat_interval: 5m
      - match:
          severity: warning
        receiver: default
        repeat_interval: 6h
      - match:
          severity: critical
        receiver: default
        repeat_interval: 3h
type: Opaque
