apiVersion: v1
kind: Service
metadata:
  name: alertmanager
spec:
  clusterIP: None
  ports:
  - name: tcp-6783
    port: 6783
  - name: tcp-9093
    port: 9093
  publishNotReadyAddresses: true
  selector:
    name: alertmanager
