apiVersion: v1
kind: Secret
metadata:
  name: grafana
stringData:
  grafana.ini: |
    app_mode = production
    instance_name = grafana
    [log]
    mode = console
    [log.console]
    level = info
    format = console
    [security]
    admin_user = admin
    admin_password = GRAFANA_ADMIN_PASSWORD
    [auth.anonymous]
    enabled = false
    org_role = Viewer
    [server]
    domain = ROOT_DOMAIN
    root_url = https://grafana.ROOT_DOMAIN
    [users]
    allow_sign_up = false
    default_theme = dark
    [database]
    type = sqlite3
    path = grafana.db
    [session]
    cookie_name = grafana_sess
    cookie_secure = true
