apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-cluster: scrape-me
  name: kube-state-metrics
spec:
  ports:
  - name: exporter-8080
    port: 8080
  - name: exporter-8081
    port: 8081
  selector:
    name: kube-state-metrics
