apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-exporter
rules:
- apiGroups:
  - policy
  resourceNames:
  - hostaccess-prometheus-monitoring-node-exporter
  resources:
  - podsecuritypolicies
  verbs:
  - use
