apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
spec:
  rules:
  - host: prometheus.ROOT_DOMAIN
    http:
      paths:
      - backend:
          serviceName: prometheus
          servicePort: 9090
