apiVersion: v1
kind: Secret
metadata:
  name: thanos-store
stringData:
  thanos.yaml: |
    type: S3
    config:
      bucket: thanos
      access_key: ACCESSKEY_SED
      endpoint: "http://minio.NAMESPACE_SED.svc.cluster.local:9000"
      insecure: true
      region: us-east-1
      secret_key: SECRETKEY_SED
      signature_version2: true
      http_config:
        idle_conn_timeout: 1m30s
        insecure_skip_verify: false
        response_header_timeout: 2m
      part_size: 134217728
      put_user_metadata: {}
      trace:
        enable: false
