groups:
- name: PrometheusJobs
  rules:
  - alert: PrometheusJobMissing
    expr: absent(up{job="cluster"})
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Prometheus job missing (instance {{ $labels.instance }})"
      description: "A Prometheus job has disappeared\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: PrometheusJobMissing
    expr: absent(up{job="kubelet"})
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Prometheus job missing (instance {{ $labels.instance }})"
      description: "A Prometheus job has disappeared\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: PrometheusJobMissing
    expr: absent(up{job="cadvisor"})
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Prometheus job missing (instance {{ $labels.instance }})"
      description: "A Prometheus job has disappeared\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: PrometheusJobMissing
    expr: absent(up{job="nodes"})
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Prometheus job missing (instance {{ $labels.instance }})"
      description: "A Prometheus job has disappeared\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: PrometheusJobMissing
    expr: absent(up{job="s3buckets"})
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Prometheus job missing (instance {{ $labels.instance }})"
      description: "A Prometheus job has disappeared\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: PrometheusJobMissing
    expr: absent(up{job="kubeci"})
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Prometheus job missing (instance {{ $labels.instance }})"
      description: "A Prometheus job has disappeared\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: PrometheusJobMissing
    expr: absent(up{job="prometheus"})
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Prometheus job missing (instance {{ $labels.instance }})"
      description: "A Prometheus job has disappeared\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
