groups:
- name: KubernetesLinkerd
  rules:
  - alert: LinkerdHighErrorRate
    expr: sum(rate(request_errors_total[5m])) by (deployment, statefulset, daemonset) / sum(rate(request_total[5m])) by (deployment, statefulset, daemonset) * 100 > 10
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Linkerd high error rate (instance {{ $labels.instance }})"
      description: "Linkerd error rate for {{ $labels.deployment | $labels.statefulset | $labels.daemonset }} is over 10%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
