groups:
- name: KubernetesNextCloud
  rules:
  - alert: NextCloudDown
    expr: nextcloud_up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "NextCloud down (instance {{ $labels.instance }})"
      description: "NextCloud instance is down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
