groups:
- name: KubernetesNexus
  rules:
  - alert: NexusDown
    expr: nexus_up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Nexus down (instance {{ $labels.instance }})"
      description: "Nexus instance is down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
