groups:
- name: KubernetesOpenldap
  rules:
  - alert: OpenldapDown
    expr: ldap_up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Openldap down (instance {{ $labels.instance }})"
      description: "Openldap instance is down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
