{
 "title": "Ansible Operator",
 "description": "Ansible Operator overview.",
 "tags": [
  "ansible",
  "kubernetes",
  "operator"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "30m,1h,3h,6h,12h,1d,7d,14d,30d" },
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(ansible_operator_reconciles_bucket,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(ansible_operator_reconciles_bucket{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "crd",
    "label": "Resource Kind",
    "query": "label_values(ansible_operator_reconciles_bucket{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},GVK)"
   },
   {
    "name": "podname",
    "label": "Kubernetes Pod Name",
    "query": "label_values(ansible_operator_reconciles_bucket{kubernetes_cluster=~\"$cluster\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Last Restart",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$podname\"})"
    }
   ]
  },
  {
   "title": "Managed CRs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(resource_created_at_seconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$podname\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"$podname\",container=~\".+\"}[5m])",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"$podname\",container=~\".+\"}",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Last CR Created",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(resource_created_at_seconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$podname\"})"
    }
   ]
  },
  {
   "title": "Managed Kinds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (kind) (resource_created_at_seconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$podname\"}))"
    }
   ]
  },
  {
   "title": "Reconcile Results in $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,GVK,result) (increase(ansible_operator_reconcile_result{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",GVK=~\"$crd\"}[$interval]))",
     "legendFormat": "{{result}} {{GVK}} {{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "Work Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,GVK,name) (workqueue_work_duration_seconds_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",GVK=~\"$crd\"} / workqueue_work_duration_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",GVK=~\"$crd\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,GVK,name) (workqueue_queue_duration_seconds_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",GVK=~\"$crd\"} / workqueue_queue_duration_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",GVK=~\"$crd\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{name}}"
    }
   ]
  },
  {
   "title": "Reconciles Count by $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,GVK) (increase(ansible_operator_reconciles_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",GVK=~\"$crd\"}[$interval]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{GVK}}"
    }
   ]
  },
  {
   "title": "Queries to API per $interval",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,url,verb) (increase(rest_client_request_latency_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[$interval]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{verb}} {{url}}"
    }
   ]
  }
 ]
}