{
 "title": "Bluemind Full",
 "description": "BlueMind Metrics full",
 "tags": [
  "application",
  "bluemind"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval (rates)",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "bluemind",
    "label": "BlueMind",
    "query": "label_values(bluemind_cluster,bmhostname)"
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (bmhostname) (processes_total{bmhostname=~\"$bluemind\"})",
     "legendFormat": "{{bmhostname}} Total"
    },
    {
     "expr": "sum by (bmhostname) (processes_blocked{bmhostname=~\"$bluemind\"})",
     "legendFormat": "{{bmhostname}} Blocked"
    },
    {
     "expr": "sum by (bmhostname) (processes_running{bmhostname=~\"$bluemind\"})",
     "legendFormat": "{{bmhostname}} Running"
    },
    {
     "expr": "sum by (bmhostname) (processes_sleeping{bmhostname=~\"$bluemind\"})",
     "legendFormat": "{{bmhostname}} Sleeping"
    },
    {
     "expr": "sum by (bmhostname) (processes_stopped{bmhostname=~\"$bluemind\"})",
     "legendFormat": "{{bmhostname}} Stopped"
    },
    {
     "expr": "sum by (bmhostname) (processes_zombies{bmhostname=~\"$bluemind\"})",
     "legendFormat": "{{bmhostname}} Zombies"
    },
    {
     "expr": "sum by (bmhostname) (processes_dead{bmhostname=~\"$bluemind\"})",
     "legendFormat": "{{bmhostname}} Dead"
    },
    {
     "expr": "sum by (bmhostname) (processes_idle{bmhostname=~\"$bluemind\"})",
     "legendFormat": "{{bmhostname}} Idle"
    }
   ]
  },
  {
   "title": "Uptime (min)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bottomk(1,system_uptime{bmhostname=~\"$bluemind\"}/(3600*24))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mem_total{bmhostname=~\"$bluemind\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(count(cpu_usage_idle{cpu=\"cpu-total\",bmhostname=~\"$bluemind\"})*100)-sum(cpu_usage_idle{cpu=\"cpu-total\",bmhostname=~\"$bluemind\"})"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * sum(mem_used{bmhostname=~\"$bluemind\"})/sum(mem_total{bmhostname=~\"$bluemind\"})"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100*((sum(mem_swap_total{bmhostname=~\"$bluemind\"})-sum(mem_swap_free{bmhostname=~\"$bluemind\"}))/(sum(mem_swap_total{bmhostname=~\"$bluemind\"})))"
    }
   ]
  },
  {
   "title": "vCPU count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(system_n_cpus{bmhostname=~\"$bluemind\"})"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load1{bmhostname=~\"$bluemind\"}",
     "legendFormat": "{{bmhostname}} Load1"
    },
    {
     "expr": "system_load5{bmhostname=~\"$bluemind\"}",
     "legendFormat": "{{bmhostname}} Load5"
    },
    {
     "expr": "system_load15{bmhostname=~\"$bluemind\"}",
     "legendFormat": "{{bmhostname}} Load15"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(mem_free{bmhostname=~\"$bluemind\"})/sum(mem_total{bmhostname=~\"$bluemind\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "100 * sum(mem_buffered{bmhostname=~\"$bluemind\"})/sum(mem_total{bmhostname=~\"$bluemind\"})",
     "legendFormat": "Buffered"
    },
    {
     "expr": "100 * sum(mem_used{bmhostname=~\"$bluemind\"})/sum(mem_total{bmhostname=~\"$bluemind\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "100 * sum(mem_cached{bmhostname=~\"$bluemind\"})/sum(mem_total{bmhostname=~\"$bluemind\"})",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(4,(100*disk_used{bmhostname=~\"$bluemind\"}/disk_total{bmhostname=~\"$bluemind\",path!=\"/var/backups/bluemind\"}))",
     "legendFormat": "{{bmhostname}}:{{path}}"
    }
   ]
  },
  {
   "title": "Top Disk IOs in $interval",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1000*topk(5,increase(diskio_read_time{bmhostname=~\"$bluemind\"}[$interval]) / increase(diskio_read_bytes{bmhostname=~\"$bluemind\"}[$interval]))",
     "legendFormat": "{{bmhostname}} / {{name}}"
    }
   ]
  },
  { "title": "Postfix", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Queued Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "postfix_queue_length{bmhostname=~\"$bluemind\",queue=\"active\"}",
     "legendFormat": "{{bmhostname}} Active"
    },
    {
     "expr": "postfix_queue_length{bmhostname=~\"$bluemind\",queue=\"deferred\"}",
     "legendFormat": "{{bmhostname}} Deferred"
    },
    {
     "expr": "postfix_queue_length{bmhostname=~\"$bluemind\",queue=\"hold\"}",
     "legendFormat": "{{bmhostname}} Hold"
    },
    {
     "expr": "postfix_queue_length{bmhostname=~\"$bluemind\",queue=\"incoming\"}",
     "legendFormat": "{{bmhostname}} Incoming"
    },
    {
     "expr": "postfix_queue_length{bmhostname=~\"$bluemind\",queue=\"maildrop\"}",
     "legendFormat": "{{bmhostname}} Maildrop"
    }
   ]
  },
  {
   "title": "Milter TX/RX per $interval",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(bm_milter_traffic_size_count{bmhostname=~\"$bluemind\"}[$interval])) by (type)",
     "legendFormat": "{{type}}    "
    }
   ]
  },
  {
   "title": "LMTP Deliveries in $interval",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(bm_lmtpd_deliveries_count{bmhostname=~\"$bluemind\"}[$interval]))"
    }
   ]
  },
  {
   "title": "LMTP OK  in $interval",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(bm_lmtpd_deliveries_count{bmhostname=~\"$bluemind\",status=\"ok\"}[$interval]))"
    }
   ]
  },
  {
   "title": "LMTP KO  in $interval",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(bm_lmtpd_deliveries_count{bmhostname=~\"$bluemind\",status=\"ko\"}[$interval]) OR ON() vector(0))"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bm_lmtpd_activeConnections{bmhostname=~\"$bluemind\"}",
     "legendFormat": "{{bmhostname}}"
    }
   ]
  },
  {
   "title": "LMTP Duplicate  in $interval",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(bm_lmtpd_deliveries_count{bmhostname=~\"$bluemind\",status=\"duplicate\"}[$interval]) OR ON() vector(0))"
    }
   ]
  },
  {
   "title": "Cumulated Messages Size in $interval",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(bm_lmtpd_emailSize_totalAmount{bmhostname=~\"$bluemind\"}[$interval])",
     "legendFormat": "{{bmhostname}}"
    }
   ]
  },
  {
   "title": "Copies sent in $interval",
   "type": "graph",
   "description": "Counts recipients",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bm_lmtpd_emailRecipients_count{bmhostname=~\"$bluemind\"}[$interval])",
     "legendFormat": "{{bmhostname}}"
    }
   ]
  },
  {
   "title": "Cyrus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "imapd_process{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "imapd_memory{bmhostname=~\"$bluemind\"} OR ON() vector(0)",
       "legendFormat": "{{bmhostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "BlueMind 4",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "JDBC Core Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (bmhostname,dbkind) (bm_core_jdbc_db_connections{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "{{bmhostname}} - {{dbkind}}"
      },
      {
       "expr": "sum by (bmhostname) (bm_core_jdbc_db_connections{bmhostname=~\"$bluemind\"}) OR ON() vector(0)",
       "legendFormat": "{{bmhostname}} -Total"
      }
     ]
    },
    {
     "title": "LDAP Auth Timers per $interval",
     "type": "graph",
     "gridPos": { "h": 7, "w": 14, "x": 10, "y": 45 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by (bmhostname,op) (increase(bm_core_ldap_auth_service_timer_count{bmhostname=~\"$bluemind\"}[$interval]) OR on() vector(0))",
       "legendFormat": "{{bmhostname}} {{op}}"
      }
     ]
    },
    {
     "title": "Messages Processed in $interval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(bm_core_cyrus_replication_applyMessage_count{bmhostname=~\"$bluemind\"}[$interval]) OR ON() vector(0)",
       "legendFormat": "{{bmhostname}}"
      }
     ]
    },
    {
     "title": "Cyrus Replication Sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bm_core_cyrus_replication_activeSessions{bmhostname=~\"$bluemind\"} OR ON() vector(0)",
       "legendFormat": "{{bmhostname}}"
      }
     ]
    },
    {
     "title": "Node Heap Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100*sum(bm_node_jvm_heapMemory_used{bmhostname=~\"$bluemind\"})/sum(bm_node_jvm_heapMemory_max{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "Node JVM Memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 21, "x": 3, "y": 60 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "bm_node_jvm_usedMemory{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Used"
      },
      {
       "expr": "bm_node_jvm_heapMemory_used{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Used"
      },
      {
       "expr": "bm_node_jvm_heapMemory_max{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Total"
      }
     ]
    },
    {
     "title": "Node Memory Usage",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(bm_node_jvm_usedMemory{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "SDS Proxy Heap Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100*sum(bm_sds_proxy_jvm_heapMemory_used{bmhostname=~\"$bluemind\"})/sum(bm_sds_proxy_jvm_heapMemory_max{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "SDS Proxy JVM Memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 21, "x": 3, "y": 70 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "bm_sds_proxy_jvm_usedMemory{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Used"
      },
      {
       "expr": "bm_sds_proxy_jvm_heapMemory_used{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Used"
      },
      {
       "expr": "bm_sds_proxy_jvm_heapMemory_max{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Max"
      }
     ]
    },
    {
     "title": "SDS Proxy Memory Usage",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(bm_sds_proxy_jvm_usedMemory{bmhostname=~\"$bluemind\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "BlueMind 3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Core Executor",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bm_core_executor_active{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(bm_core_executor_queued{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Queued"
      },
      {
       "expr": "sum(bm_core_executor_rejected{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Rejected"
      },
      {
       "expr": "sum(bm_core_executor_timedOut{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Timed Out"
      }
     ]
    },
    {
     "title": "EAS executor",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bm_eas_executor_active{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(bm_eas_executor_queued{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Queued"
      },
      {
       "expr": "sum(bm_eas_executor_rejected{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Rejected"
      },
      {
       "expr": "sum(bm_eas_executor_timedOut{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Timed Out"
      }
     ]
    },
    {
     "title": "HPS Executor",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bm_hps_executor_active{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(bm_hps_executor_queued{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Queued"
      },
      {
       "expr": "sum(bm_hps_executor_rejected{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Rejected"
      },
      {
       "expr": "sum(bm_hps_executor_timedOut{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Timed Out"
      }
     ]
    },
    {
     "title": "IPS Executor",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bm_ips_executor_active{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(bm_ips_executor_queued{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Queued"
      },
      {
       "expr": "sum(bm_ips_executor_rejected{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Rejected"
      },
      {
       "expr": "sum(bm_ips_executor_timedOut{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Timed Out"
      }
     ]
    },
    {
     "title": "LMTPD Executor",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bm_lmtpd_executor_active{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(bm_lmtpd_executor_queued{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Queued"
      },
      {
       "expr": "sum(bm_lmtpd_executor_rejected{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Rejected"
      },
      {
       "expr": "sum(bm_lmtpd_executor_timedOut{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Timed Out"
      }
     ]
    },
    {
     "title": "Locator Executor",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bm_locator_executor_active{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(bm_locator_executor_queued{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Queued"
      },
      {
       "expr": "sum(bm_locator_executor_rejected{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Rejected"
      },
      {
       "expr": "sum(bm_locator_executor_timedOut{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Timed Out"
      }
     ]
    },
    {
     "title": "Milter Executor",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bm_milter_executor_active{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(bm_milter_executor_queued{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Queued"
      },
      {
       "expr": "sum(bm_milter_executor_rejected{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Rejected"
      },
      {
       "expr": "sum(bm_milter_executor_timedOut{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Timed Out"
      }
     ]
    },
    {
     "title": "WebServer Executor",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (bm_webserver_executor_active{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Active {{name}}"
      },
      {
       "expr": "sum by (name) (bm_webserver_executor_queued{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Queued {{name}}"
      },
      {
       "expr": "sum by (name) (bm_webserver_executor_rejected{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Rejected {{name}}"
      },
      {
       "expr": "sum by (name) (bm_webserver_executor_timedOut{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Timed Out {{name}}"
      }
     ]
    },
    {
     "title": "XMPP Executor",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bm_xmpp_executor_active{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Active"
      },
      {
       "expr": "sum (bm_xmpp_executor_queued{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Queued"
      },
      {
       "expr": "sum (bm_xmpp_executor_rejected{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Rejected"
      },
      {
       "expr": "sum (bm_xmpp_executor_timedOut{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Timed Out"
      }
     ]
    },
    {
     "title": "YSNP Executor",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (bm_ysnp_executor_active{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Active"
      },
      {
       "expr": "sum (bm_ysnp_executor_queued{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Queued"
      },
      {
       "expr": "sum (bm_ysnp_executor_rejected{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Rejected"
      },
      {
       "expr": "sum (bm_ysnp_executor_timedOut{bmhostname=~\"$bluemind\"} OR ON() vector(0))",
       "legendFormat": "Timed Out"
      }
     ]
    },
    {
     "title": "IPS Heap Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100*sum(bm_ips_jvm_heapMemory_used{bmhostname=~\"$bluemind\"})/sum(bm_ips_jvm_heapMemory_max{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "IPS JVM Memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 21, "x": 3, "y": 38 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "bm_ips_jvm_usedMemory{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Used"
      },
      {
       "expr": "bm_ips_jvm_heapMemory_used{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Used"
      },
      {
       "expr": "bm_ips_jvm_heapMemory_max{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Max"
      }
     ]
    },
    {
     "title": "IPS Memory Usage",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(bm_ips_jvm_usedMemory{bmhostname=~\"$bluemind\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "ElasticSearch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Opened Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(elasticsearch_http_current_open{bmhostname=~\"$bluemind\"})",
       "legendFormat": "Active"
      }
     ]
    },
    {
     "title": "Total Documents by Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(elasticsearch_clusterstats_indices_docs_count{bmhostname=~\"$bluemind\",status=\"green\"})",
       "legendFormat": "GREEN"
      },
      {
       "expr": "sum(elasticsearch_clusterstats_indices_docs_count{bmhostname=~\"$bluemind\",status=\"red\"})",
       "legendFormat": "RED"
      }
     ]
    },
    {
     "title": "Queries",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(elasticsearch_indices_search_scroll_current{bmhostname=~\"$bluemind\"})",
       "legendFormat": "Scroll"
      },
      {
       "expr": "sum(elasticsearch_indices_search_fetch_current{bmhostname=~\"$bluemind\"})",
       "legendFormat": "Fetch"
      },
      {
       "expr": "sum(elasticsearch_indices_search_suggest_current{bmhostname=~\"$bluemind\"})",
       "legendFormat": "Suggest"
      },
      {
       "expr": "sum(elasticsearch_indices_search_query_current{bmhostname=~\"$bluemind\"})",
       "legendFormat": "Query"
      }
     ]
    },
    {
     "title": "Documents Inserted per $interval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_clusterstats_indices_docs_count{bmhostname=~\"$bluemind\",status=\"green\"}[1m]))",
       "legendFormat": "GREEN"
      },
      {
       "expr": "sum(rate(elasticsearch_clusterstats_indices_docs_count{bmhostname=~\"$bluemind\",status=\"red\"}[1m]))",
       "legendFormat": "RED"
      }
     ]
    }
   ]
  },
  {
   "title": "HPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Auth per $interval",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(bm_hps_authCount_count{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}}"
      }
     ]
    },
    {
     "title": "HeartBeat per $interval",
     "type": "graph",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(bm_hps_heartbeat_receiver_received_count{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} Received"
      },
      {
       "expr": "increase(bm_hps_heartbeat_receiver_failures_count{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} Failed"
      }
     ]
    },
    {
     "title": "Accesses per $interval",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(bm_hps_requestsCount_count{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} {{kind}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Locator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Accesses per $interval",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(bm_locator_requestsCount_count{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} {{origin}} {{statusCode}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections in $interval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_accepts{bmhostname=~\"$bluemind\"}[$interval]))",
       "legendFormat": "Accepts"
      },
      {
       "expr": "sum(rate(nginx_active{bmhostname=~\"$bluemind\"}[$interval]))",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(rate(nginx_handled{bmhostname=~\"$bluemind\"}[$interval]))",
       "legendFormat": "Handled"
      },
      {
       "expr": "sum(rate(nginx_reading{bmhostname=~\"$bluemind\"}[$interval]))",
       "legendFormat": "Reading"
      },
      {
       "expr": "sum(rate(nginx_waiting{bmhostname=~\"$bluemind\"}[$interval]))",
       "legendFormat": "Waiting"
      },
      {
       "expr": "sum(rate(nginx_writing{bmhostname=~\"$bluemind\"}[$interval]))",
       "legendFormat": "Writing"
      }
     ]
    },
    {
     "title": "Total Requests in $interval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_requests{bmhostname=~\"$bluemind\"}[$interval]))"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "HeartBeats",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "bm_eas_heartbeat_receiver_age{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Core"
      },
      {
       "expr": "bm_hps_heartbeat_receiver_age{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} EAS"
      },
      {
       "expr": "bm_ips_heartbeat_receiver_age{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} IPS"
      },
      {
       "expr": "bm_lmtpd_heartbeat_receiver_age{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} LMTPD"
      },
      {
       "expr": "bm_milter_heartbeat_receiver_age{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Milter"
      },
      {
       "expr": "bm_webserver_heartbeat_receiver_age{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} WebServer"
      },
      {
       "expr": "bm_xmpp_heartbeat_receiver_age{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} XMPP"
      },
      {
       "expr": "bm_ysnp_heartbeat_receiver_age{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} YSNP"
      }
     ]
    },
    {
     "title": "HeartBeats Sent per $interval",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(bm_core_heartbeat_broadcast_count{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} {{state}}"
      }
     ]
    },
    {
     "title": "HeartBeats Failures per $interval",
     "type": "graph",
     "gridPos": { "h": 6, "w": 13, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(bm_eas_heartbeat_receiver_failures_count{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} Core"
      },
      {
       "expr": "increase(bm_hps_heartbeat_receiver_failures_count{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} EAS"
      },
      {
       "expr": "increase(bm_ips_heartbeat_receiver_failures_count{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} IPS"
      },
      {
       "expr": "increase(bm_lmtpd_heartbeat_receiver_failures_count{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} LMTPD"
      },
      {
       "expr": "increase(bm_milter_heartbeat_receiver_failures_count{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} Milter"
      },
      {
       "expr": "increase(bm_webserver_heartbeat_receiver_failures_count{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} WebServer"
      },
      {
       "expr": "increase(bm_xmpp_heartbeat_receiver_failures_count{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} XMPP"
      },
      {
       "expr": "increase(bm_ysnp_heartbeat_receiver_failures_count{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} YSNP"
      }
     ]
    },
    {
     "title": "Crashes Counters (hprofs)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bm_core_hprof{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Core"
      },
      {
       "expr": "bm_eas_hprof{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} EAS"
      },
      {
       "expr": "bm_ips_hprof{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} IPS"
      },
      {
       "expr": "bm_lmtpd_hprof{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} LMTPD"
      },
      {
       "expr": "bm_milter_hprof{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Milter"
      },
      {
       "expr": "bm_node_hprof{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Node"
      },
      {
       "expr": "bm_sds_proxy_hprof{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} SDS Proxy"
      },
      {
       "expr": "bm_tika_hprof{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Tika"
      },
      {
       "expr": "bm_webserver_hprof{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} WebServer"
      },
      {
       "expr": "bm_xmpp_hprof{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} XMPP"
      },
      {
       "expr": "bm_ysnp_hprof{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} YSNP"
      },
      {
       "expr": "bm_elasticsearch_hprof{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} ElasticSearch"
      },
      {
       "expr": "bm_hps_hprof{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} HPS"
      }
     ]
    },
    {
     "title": "Core Heap Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100*sum(bm_core_jvm_heapMemory_used{bmhostname=~\"$bluemind\"})/sum(bm_core_jvm_heapMemory_max{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "Core JVM Memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 21, "x": 3, "y": 48 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "bm_core_jvm_usedMemory{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Used"
      },
      {
       "expr": "bm_core_jvm_heapMemory_used{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Used"
      },
      {
       "expr": "bm_core_jvm_heapMemory_max{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Max"
      }
     ]
    },
    {
     "title": "Core Memory Usage",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(bm_core_jvm_usedMemory{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "EAS Heap Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100*sum(bm_eas_jvm_heapMemory_used{bmhostname=~\"$bluemind\"})/sum(bm_eas_jvm_heapMemory_max{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "EAS JVM Memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 21, "x": 3, "y": 58 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "bm_eas_jvm_usedMemory{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Used"
      },
      {
       "expr": "bm_eas_jvm_heapMemory_used{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Used"
      },
      {
       "expr": "bm_eas_jvm_heapMemory_max{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Max"
      }
     ]
    },
    {
     "title": "EAS Memory Usage",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(bm_eas_jvm_usedMemory{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "ElasticSearch Heap Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(elasticsearch_jvm_mem_heap_used_in_bytes{bmhostname=~\"$bluemind\"})/sum(elasticsearch_jvm_mem_heap_max_in_bytes{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "ElasticSearch JVM Memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 21, "x": 3, "y": 68 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by (bmhostname) (elasticsearch_jvm_mem_non_heap_used_in_bytes{bmhostname=~\"$bluemind\"})",
       "legendFormat": "{{bmhostname}} Used"
      },
      {
       "expr": "sum by (bmhostname) (elasticsearch_jvm_mem_heap_used_in_bytes{bmhostname=~\"$bluemind\"})",
       "legendFormat": "{{bmhostname}} Heap Used"
      },
      {
       "expr": "sum by (bmhostname) (elasticsearch_jvm_mem_heap_max_in_bytes{bmhostname=~\"$bluemind\"})",
       "legendFormat": "{{bmhostname}} Heap Total"
      }
     ]
    },
    {
     "title": "ElasticSearch Memory Usage",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(elasticsearch_jvm_mem_non_heap_used_in_bytes{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "HPS Heap Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100*sum(bm_hps_jvm_heapMemory_used{bmhostname=~\"$bluemind\"})/sum(bm_hps_jvm_heapMemory_max{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "HPS JVM Memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 21, "x": 3, "y": 78 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "bm_hps_jvm_usedMemory{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Used"
      },
      {
       "expr": "bm_hps_jvm_heapMemory_used{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Used"
      },
      {
       "expr": "bm_hps_jvm_heapMemory_max{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Max"
      }
     ]
    },
    {
     "title": "HPS Memory Usage",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(bm_hps_jvm_usedMemory{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "Milter Heap Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100*sum(bm_milter_jvm_heapMemory_used{bmhostname=~\"$bluemind\"})/sum(bm_milter_jvm_heapMemory_max{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "Milter JVM Memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 21, "x": 3, "y": 88 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "bm_milter_jvm_usedMemory{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Used"
      },
      {
       "expr": "bm_milter_jvm_heapMemory_used{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Used"
      },
      {
       "expr": "bm_milter_jvm_heapMemory_max{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Max"
      }
     ]
    },
    {
     "title": "Milter Memory Usage",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(bm_milter_jvm_usedMemory{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "LMTPD Heap Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100*sum(bm_lmtpd_jvm_heapMemory_used{bmhostname=~\"$bluemind\"})/sum(bm_lmtpd_jvm_heapMemory_max{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "LMTPD JVM Memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 21, "x": 3, "y": 98 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "bm_lmtpd_jvm_usedMemory{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Used"
      },
      {
       "expr": "bm_lmtpd_jvm_heapMemory_used{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Used"
      },
      {
       "expr": "bm_milter_jvm_heapMemory_max{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Total"
      }
     ]
    },
    {
     "title": "LMTPD Memory Usage",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(bm_lmtpd_jvm_usedMemory{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "Locator Heap Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100*sum(bm_locator_jvm_heapMemory_used{bmhostname=~\"$bluemind\"})/sum(bm_locator_jvm_heapMemory_max{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "Locator JVM Memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 21, "x": 3, "y": 108 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "bm_locator_jvm_usedMemory{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Used"
      },
      {
       "expr": "bm_locator_jvm_heapMemory_used{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Used"
      },
      {
       "expr": "bm_locator_jvm_heapMemory_max{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Total"
      }
     ]
    },
    {
     "title": "Locator Memory Usage",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(bm_locator_jvm_usedMemory{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "WebServer Heap Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100*sum(bm_webserver_jvm_heapMemory_used{bmhostname=~\"$bluemind\"})/sum(bm_webserver_jvm_heapMemory_max{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "Webserver JVM Memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 21, "x": 3, "y": 118 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "bm_webserver_jvm_usedMemory{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Used"
      },
      {
       "expr": "bm_webserver_jvm_heapMemory_used{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Used"
      },
      {
       "expr": "bm_webserver_jvm_heapMemory_max{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Max"
      }
     ]
    },
    {
     "title": "WebServer Memory Usage",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(bm_webserver_jvm_usedMemory{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "YSNP Heap Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100*sum(bm_ysnp_jvm_heapMemory_used{bmhostname=~\"$bluemind\"})/sum(bm_ysnp_jvm_heapMemory_max{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "YSNP JVM Memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 21, "x": 3, "y": 128 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "bm_ysnp_jvm_usedMemory{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Used"
      },
      {
       "expr": "bm_ysnp_jvm_heapMemory_used{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Used"
      },
      {
       "expr": "bm_ysnp_jvm_heapMemory_max{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Max"
      }
     ]
    },
    {
     "title": "YSNP Memory Usage",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(bm_ysnp_jvm_usedMemory{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "XMPP Heap Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100*sum(bm_xmpp_jvm_heapMemory_used{bmhostname=~\"$bluemind\"})/sum(bm_xmpp_jvm_heapMemory_max{bmhostname=~\"$bluemind\"})"
      }
     ]
    },
    {
     "title": "XMPP JVM Memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 21, "x": 3, "y": 138 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "bm_xmpp_jvm_usedMemory{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Used"
      },
      {
       "expr": "bm_xmpp_jvm_heapMemory_used{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Used"
      },
      {
       "expr": "bm_xmpp_jvm_heapMemory_max{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Heap Total"
      }
     ]
    },
    {
     "title": "XMPP Memory Usage",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(bm_xmpp_jvm_usedMemory{bmhostname=~\"$bluemind\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "MemCache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Items",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 134 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(memcached_total_items{bmhostname=~\"$bluemind\"})",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "New Items per $interval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 134 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(memcached_total_items{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}}"
      }
     ]
    },
    {
     "title": "Total Objects Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 134 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "memcached_bytes{bmhostname=~\"$bluemind\"}",
       "legendFormat": "{{bmhostname}} Read"
      }
     ]
    },
    {
     "title": "Connections per $interval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 134 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(memcached_total_connections{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} "
      }
     ]
    },
    {
     "title": "New Items in $interval",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 138 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(memcached_total_items{bmhostname=~\"$bluemind\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Hits & Misses in $interval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(memcached_cas_hits{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} Cas Hits"
      },
      {
       "expr": "rate(memcached_cas_misses{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} Cas Misses"
      },
      {
       "expr": "rate(memcached_decr_hits{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} Decr Hits"
      },
      {
       "expr": "rate(memcached_decr_misses{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} Decr Misses"
      },
      {
       "expr": "rate(memcached_delete_hits{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} Delete Hits"
      },
      {
       "expr": "rate(memcached_delete_misses{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} Delete Misses"
      },
      {
       "expr": "rate(memcached_get_hits{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} Get Hits"
      },
      {
       "expr": "rate(memcached_get_misses{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} Get Misses"
      },
      {
       "expr": "rate(memcached_incr_hits{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} Incr Hits"
      },
      {
       "expr": "rate(memcached_incr_misses{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} Incr Misses"
      },
      {
       "expr": "rate(memcached_touch_hits{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} Touch Hits"
      },
      {
       "expr": "rate(memcached_touch_misses{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} Touch Misses"
      }
     ]
    },
    {
     "title": "Read / Write in $interval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(memcached_bytes_read{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} Read"
      },
      {
       "expr": "rate(memcached_bytes_written{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} Written"
      }
     ]
    }
   ]
  },
  { "title": "PHP-FPM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_active_processes{bmhostname=~\"$bluemind\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(phpfpm_idle_processes{bmhostname=~\"$bluemind\"})",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(phpfpm_idle_processes{bmhostname=~\"$bluemind\"}+phpfpm_active_processes{bmhostname=~\"$bluemind\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Workers Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "phpfpm_listen_queue{bmhostname=~\"$bluemind\"}",
     "legendFormat": "{{bmhostname}} Used"
    },
    {
     "expr": "phpfpm_listen_queue_len{bmhostname=~\"$bluemind\"}",
     "legendFormat": "{{bmhostname}} Total"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "fpm_memory{bmhostname=~\"$bluemind\"} OR on() vector(0)",
     "legendFormat": "{{bmhostname}} Used"
    }
   ]
  },
  {
   "title": "Accepted Connection per $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(phpfpm_accepted_conn{bmhostname=~\"$bluemind\"}[$interval])",
     "legendFormat": "{{bmhostname}}"
    }
   ]
  },
  {
   "title": "Slow Requests in $interval",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(phpfpm_slow_requests{bmhostname=~\"$bluemind\"}[$interval])",
     "legendFormat": "{{bmhostname}}"
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "postgresql_buffers_alloc{bmhostname=~\"$bluemind\", server=~\"dbname=bj host=localhost user=bj\"}",
       "legendFormat": "{{bmhostname}} Allocated"
      },
      {
       "expr": "postgresql_buffers_clean{bmhostname=~\"$bluemind\", server=\"dbname=bj host=localhost user=bj\"}",
       "legendFormat": "{{bmhostname}} Clean"
      },
      {
       "expr": "postgresql_buffers_checkpoint{bmhostname=~\"$bluemind\", server=\"dbname=bj host=localhost user=bj\"}",
       "legendFormat": "{{bmhostname}} Checkpoint"
      },
      {
       "expr": "postgresql_buffers_backend{bmhostname=~\"$bluemind\", server=\"dbname=bj host=localhost user=bj\"}",
       "legendFormat": "{{bmhostname}} Backend"
      },
      {
       "expr": "postgresql_buffers_backend_fsync{bmhostname=~\"$bluemind\", server=\"dbname=bj host=localhost user=bj\"}",
       "legendFormat": "{{bmhostname}} Backend Fsync"
      }
     ]
    },
    {
     "title": "Conflicts & Deadlocks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (bmhostname,datname) (postgresql_deadlocks{bmhostname=~\"$bluemind\",server=\"dbname=bj host=localhost user=bj\"})",
       "legendFormat": "{{bmhostname}} DeadLocks on {{datname}}"
      },
      {
       "expr": "sum by (bmhostname,datname) (postgresql_conflicts{bmhostname=~\"$bluemind\",server=\"dbname=bj host=localhost user=bj\"})",
       "legendFormat": "{{bmhostname}} Conflicts on {{datname}}"
      }
     ]
    },
    {
     "title": "Commits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (bmhostname,db) (rate(postgresql_xact_commit{bmhostname=~\"$bluemind\",server=\"dbname=bj host=localhost user=bj\"}[$interval]))",
       "legendFormat": "{{bmhostname}} {{db}}"
      }
     ]
    },
    {
     "title": "Rows",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "none", "label": "tuples" }
     ],
     "targets": [
      {
       "expr": "sum by (bmhostname,db) (rate(postgresql_tup_returned{bmhostname=~\"$bluemind\",server=\"dbname=bj host=localhost user=bj\"}[$interval]))",
       "legendFormat": "{{bmhostname}} Returned in {{db}}"
      },
      {
       "expr": "sum by (bmhostname,db) (rate(postgresql_tup_fetched{bmhostname=~\"$bluemind\",server=\"dbname=bj host=localhost user=bj\"}[$interval]))",
       "legendFormat": "{{bmhostname}} Fetched in {{db}}"
      },
      {
       "expr": "sum by (bmhostname,db) (rate(postgresql_tup_inserted{bmhostname=~\"$bluemind\",server=\"dbname=bj host=localhost user=bj\"}[$interval]))",
       "legendFormat": "{{bmhostname}} Inserted in {{db}}"
      },
      {
       "expr": "sum by (bmhostname,db) (rate(postgresql_tup_updated{bmhostname=~\"$bluemind\",server=\"dbname=bj host=localhost user=bj\"}[$interval]))",
       "legendFormat": "{{bmhostname}} Updated in {{db}}"
      }
     ]
    }
   ]
  },
  {
   "title": "YSNP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Auth in $interval",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(bm_ysnp_authCount_count{bmhostname=~\"$bluemind\"}[$interval])",
       "legendFormat": "{{bmhostname}} @{{service}} {{status}}"
      }
     ]
    }
   ]
  }
 ]
}