{
 "title": "Bluemind",
 "description": "BlueMind Metrics overview",
 "tags": [
  "application",
  "bluemind"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval (rates)",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "bluemind",
    "label": "BlueMind",
    "query": "label_values(bluemind_cluster,bmhostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage Breakdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(mem_free{bmhostname=~\"$bluemind\"})/sum(mem_total{bmhostname=~\"$bluemind\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "100 * sum(mem_buffered{bmhostname=~\"$bluemind\"})/sum(mem_total{bmhostname=~\"$bluemind\"})",
     "legendFormat": "Buffered"
    },
    {
     "expr": "100 * sum(mem_used{bmhostname=~\"$bluemind\"})/sum(mem_total{bmhostname=~\"$bluemind\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "100 * sum(mem_cached{bmhostname=~\"$bluemind\"})/sum(mem_total{bmhostname=~\"$bluemind\"})",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(count(cpu_usage_idle{cpu=\"cpu-total\",bmhostname=~\"$bluemind\"})*100)-sum(cpu_usage_idle{cpu=\"cpu-total\",bmhostname=~\"$bluemind\"})"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(4,(100*disk_used{bmhostname=~\"$bluemind\"}/disk_total{bmhostname=~\"$bluemind\",path!=\"/var/backups/bluemind\"}))",
     "legendFormat": "{{bmhostname}}:{{path}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * sum(mem_used{bmhostname=~\"$bluemind\"})/sum(mem_total{bmhostname=~\"$bluemind\"})"
    }
   ]
  },
  {
   "title": "Queued Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "postfix_queue_length{bmhostname=~\"$bluemind\",queue=\"active\"}",
     "legendFormat": "{{bmhostname}} Active"
    },
    {
     "expr": "postfix_queue_length{bmhostname=~\"$bluemind\",queue=\"deferred\"}",
     "legendFormat": "{{bmhostname}} Deferred"
    },
    {
     "expr": "postfix_queue_length{bmhostname=~\"$bluemind\",queue=\"hold\"}",
     "legendFormat": "{{bmhostname}} Hold"
    },
    {
     "expr": "postfix_queue_length{bmhostname=~\"$bluemind\",queue=\"incoming\"}",
     "legendFormat": "{{bmhostname}} Incoming"
    },
    {
     "expr": "postfix_queue_length{bmhostname=~\"$bluemind\",queue=\"maildrop\"}",
     "legendFormat": "{{bmhostname}} Maildrop"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load1{bmhostname=~\"$bluemind\"}",
     "legendFormat": "{{bmhostname}}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100*((sum(mem_swap_total{bmhostname=~\"$bluemind\"})-sum(mem_swap_free{bmhostname=~\"$bluemind\"}))/(sum(mem_swap_total{bmhostname=~\"$bluemind\"})))"
    }
   ]
  },
  {
   "title": "Cumulated Messages Size in $interval",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(bm_lmtpd_emailSize_totalAmount{bmhostname=~\"$bluemind\"}[$interval])",
     "legendFormat": "{{bmhostname}}"
    }
   ]
  },
  {
   "title": "Copies sent in $interval",
   "type": "graph",
   "description": "Counts recipients",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bm_lmtpd_emailRecipients_count{bmhostname=~\"$bluemind\"}[$interval])",
     "legendFormat": "{{bmhostname}}"
    }
   ]
  }
 ]
}