{
 "title": "Ceph OSD Performance",
 "description": "Ceph OSDs performance overview.",
 "tags": [
  "ceph",
  "cluster",
  "osd",
  "storage"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(ceph_osd_metadata,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(ceph_osd_metadata{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "osd",
    "label": "OSD",
    "query": "label_values(ceph_osd_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},ceph_daemon)"
   }
  ]
 },
 "panels": [
  { "title": "OSD Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$osd Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,ceph_daemon) (irate(ceph_osd_op_r_latency_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]) / on (ceph_daemon) irate(ceph_osd_op_r_latency_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]))",
     "legendFormat": "{{ceph_daemon}} read"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,ceph_daemon) (irate(ceph_osd_op_w_latency_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]) / on (ceph_daemon) irate(ceph_osd_op_w_latency_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]))",
     "legendFormat": "{{ceph_daemon}} write"
    }
   ]
  },
  {
   "title": "$osd R/W IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,ceph_daemon) (irate(ceph_osd_op_r{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]))",
     "legendFormat": "{{ceph_daemon}} Reads"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,ceph_daemon) (irate(ceph_osd_op_w{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]))",
     "legendFormat": "{{ceph_daemon}} Writes"
    }
   ]
  },
  {
   "title": "$osd R/W Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,ceph_daemon) (irate(ceph_osd_op_r_out_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]))",
     "legendFormat": "{{ceph_daemon}} Read"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,ceph_daemon) (irate(ceph_osd_op_w_in_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]))",
     "legendFormat": "{{ceph_daemon}} Written"
    }
   ]
  },
  { "title": "Physical Device Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Physical Device Latency for $osd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "(irate(node_disk_read_time_seconds_total[1m]) / irate(node_disk_reads_completed_total[1m]) and on (instance, device) label_replace(label_replace(ceph_disk_occupation{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1:9100\", \"exported_instance\", \"(.*)\"))",
     "legendFormat": "{{instance}}/{{device}} Reads"
    },
    {
     "expr": "(irate(node_disk_write_time_seconds_total[1m]) / irate(node_disk_writes_completed_total[1m]) and on (instance, device) label_replace(label_replace(ceph_disk_occupation{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1:9100\", \"exported_instance\", \"(.*)\"))",
     "legendFormat": "{{instance}}/{{device}} Writes"
    }
   ]
  },
  {
   "title": "Physical Device R/W IOPS for $osd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total[1m]) and on (instance, device) label_replace(label_replace(ceph_disk_occupation{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1:9100\", \"exported_instance\", \"(.*)\")",
     "legendFormat": "{{device}} on {{instance}} Writes"
    },
    {
     "expr": "irate(node_disk_reads_completed_total[1m]) and on (instance, device) label_replace(label_replace(ceph_disk_occupation{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1:9100\", \"exported_instance\", \"(.*)\")",
     "legendFormat": "{{device}} on {{instance}} Reads"
    }
   ]
  },
  {
   "title": "Physical Device R/W Bytes for $osd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total[1m]) and on (instance, device) label_replace(label_replace(ceph_disk_occupation{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1:9100\", \"exported_instance\", \"(.*)\")",
     "legendFormat": "{{instance}} {{device}} Reads"
    },
    {
     "expr": "irate(node_disk_written_bytes_total[1m]) and on (instance, device) label_replace(label_replace(ceph_disk_occupation{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1:9100\", \"exported_instance\", \"(.*)\")",
     "legendFormat": "{{instance}} {{device}} Writes"
    }
   ]
  },
  {
   "title": "Physical Device Util% for $osd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total[1m]) and on (instance, device) label_replace(label_replace(ceph_disk_occupation{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1:9100\", \"exported_instance\", \"(.*)\")",
     "legendFormat": "{{device}} on {{instance}}"
    }
   ]
  }
 ]
}