{
 "title": "Ceph OSD",
 "description": "Ceph OSDs overview.",
 "tags": [
  "ceph",
  "cluster",
  "osd",
  "storage"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(ceph_health_status,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(ceph_health_status{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "osd",
    "label": "Ceph OSD",
    "query": "label_values(ceph_osd_op{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},ceph_daemon)"
   }
  ]
 },
 "panels": [
  {
   "title": "OSD Read Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg (irate(ceph_osd_op_r_latency_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]) / on (ceph_daemon) irate(ceph_osd_op_r_latency_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]) * 1000)",
     "legendFormat": "AVG read"
    },
    {
     "expr": "max (irate(ceph_osd_op_r_latency_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]) / on (ceph_daemon) irate(ceph_osd_op_r_latency_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]) * 1000)",
     "legendFormat": "MAX read"
    },
    {
     "expr": "quantile(0.95, (irate(ceph_osd_op_r_latency_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]) / on (ceph_daemon) irate(ceph_osd_op_r_latency_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]) * 1000))",
     "legendFormat": "@95%ile"
    }
   ]
  },
  {
   "title": "Highest READ Latencies",
   "type": "table-old",
   "description": "This table shows the osd's that are delivering the 10 highest read latencies within the cluster",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, (irate(ceph_osd_op_r_latency_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]) / on (ceph_daemon) irate(ceph_osd_op_r_latency_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]) * 1000))"
    }
   ]
  },
  {
   "title": "OSD Write Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg (irate(ceph_osd_op_w_latency_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]) / on (ceph_daemon) irate(ceph_osd_op_w_latency_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]) * 1000)",
     "legendFormat": "AVG write"
    },
    {
     "expr": "max (irate(ceph_osd_op_w_latency_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]) / on (ceph_daemon) irate(ceph_osd_op_w_latency_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]) * 1000)",
     "legendFormat": "MAX write"
    },
    {
     "expr": "quantile(0.95, (irate(ceph_osd_op_w_latency_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]) / on (ceph_daemon) irate(ceph_osd_op_w_latency_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]) * 1000))",
     "legendFormat": "@95%ile write"
    }
   ]
  },
  {
   "title": "Highest WRITE Latencies",
   "type": "table-old",
   "description": "This table shows the osd's that are delivering the 10 highest write latencies within the cluster",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, (sort((irate(ceph_osd_op_w_latency_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]) / on (ceph_daemon) irate(ceph_osd_op_w_latency_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}[1m]) * 1000))))"
    }
   ]
  },
  {
   "title": "OSD Types Summary",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count (ceph_osd_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\",device_class=\"hdd\"}) OR on () vector(0)",
     "legendFormat": "hdd"
    },
    {
     "expr": "count (ceph_osd_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\",device_class=\"ssd\"}) OR on () vector(0)",
     "legendFormat": "ssd"
    }
   ]
  },
  {
   "title": "OSD Objectstore Types",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ceph_bluefs_wal_total_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"})",
     "legendFormat": "bluestore"
    },
    {
     "expr": "count(ceph_osd_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}) - count(ceph_bluefs_wal_total_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"})",
     "legendFormat": "filestore"
    },
    {
     "expr": "absent(ceph_bluefs_wal_total_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"})*count(ceph_osd_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"})",
     "legendFormat": "filestore"
    }
   ]
  },
  {
   "title": "OSD Size Summary",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_stat_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"} < 1099511627776)",
     "legendFormat": "<1 TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"} >= 1099511627776 < 2199023255552)",
     "legendFormat": "<2 TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"} >= 2199023255552 < 3298534883328)",
     "legendFormat": "<3TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"} >= 3298534883328 < 4398046511104)",
     "legendFormat": "<4TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"} >= 4398046511104 < 6597069766656)",
     "legendFormat": "<6TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"} >= 6597069766656 < 8796093022208)",
     "legendFormat": "<8TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"} >= 8796093022208 < 10995116277760)",
     "legendFormat": "<10TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"} >= 10995116277760 < 13194139533312)",
     "legendFormat": "<12TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"} >= 13194139533312)",
     "legendFormat": "12TB+"
    }
   ]
  },
  {
   "title": "Distribution of PGs per OSD",
   "type": "graph",
   "description": "Each bar indicates the number of OSD's that have a PG count in a specific range as shown on the x axis.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "# of OSDs" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_numpg{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",ceph_daemon=~\"$osd\"}",
     "legendFormat": "PGs per OSD"
    }
   ]
  },
  { "title": "R/W Profile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Read/Write Profile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(ceph_pool_rd{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[60s])))",
     "legendFormat": "Reads"
    },
    {
     "expr": "round(sum(irate(ceph_pool_wr{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[60s])))",
     "legendFormat": "Writes"
    }
   ]
  }
 ]
}