{
 "title": "Ceph Cluster Details",
 "description": "Ceph Cluster Detailed overview.",
 "tags": [
  "ceph",
  "cluster",
  "storage"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(ceph_mon_quorum_status,kubernetes_cluster)"
   },
   {
    "name": "instance",
    "label": "MDS Node",
    "query": "label_values(ceph_mon_quorum_status{kubernetes_cluster=~\"$cluster\"},instance)"
   }
  ]
 },
 "panels": [
  { "title": "CLUSTER STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ceph_health_status{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_mon_quorum_status{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_pool_quota_bytes{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_bytes{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_used_bytes{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_used_bytes{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})/sum(ceph_cluster_total_bytes{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "OSD STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "OSDs IN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_in{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "OSDs OUT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}) - count(ceph_osd_in{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_up{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"} == 0) OR vector(0)"
    }
   ]
  },
  {
   "title": "Agerage PGs per OSD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_numpg{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Average OSD Apply Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Average OSD Commit Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Average Monitor Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ceph_paxos_refresh_latency_sum{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[$interval]))/clamp_min(sum(increase(ceph_paxos_refresh_latency_count{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[$interval])),1)"
    }
   ]
  },
  { "title": "CLUSTER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_bytes{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}-ceph_cluster_total_used_bytes{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(ceph_cluster_total_used_bytes{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(ceph_cluster_total_bytes{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Total Capacity"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ceph_osd_op_r{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[$interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(ceph_osd_op_w{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[$interval]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(rate(ceph_osd_op_rw{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[$interval]))",
     "legendFormat": "overwrite"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[$interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[$interval]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(irate(ceph_osd_op_rw_in_bytes{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[$interval]))",
     "legendFormat": "overwrite"
    }
   ]
  },
  {
   "title": "Objects Hourly Increase",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ceph_pool_objects{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[1h]))",
     "legendFormat": "Objects"
    }
   ]
  },
  {
   "title": "Capacity Hourly Increase",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ceph_cluster_total_used_bytes{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[1h]))",
     "legendFormat": "Capacity"
    }
   ]
  },
  { "title": "RGW STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }, "repeat": "job" },
  {
   "title": "RGW REQUEST",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_rgw_req{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Req"
    }
   ]
  },
  {
   "title": "Cache Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_rgw_cache_hit{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Hit"
    },
    {
     "expr": "sum(irate(ceph_rgw_cache_miss{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Miss"
    }
   ]
  },
  {
   "title": "RadosGW QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_rgw_get{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[$interval]))",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(irate(ceph_rgw_put{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[$interval]))",
     "legendFormat": "PUT"
    }
   ]
  },
  {
   "title": "RadosGW ThroughPut",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_rgw_get_b{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[$interval]))",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(irate(ceph_rgw_put_b{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[$interval]))",
     "legendFormat": "PUT"
    }
   ]
  },
  { "title": "RocksDB STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }, "repeat": "job" },
  {
   "title": "BlueFS Log Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ceph_daemon) (ceph_bluefs_log_bytes{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "RocksDB GET",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_rocksdb_get{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[$interval]))",
     "legendFormat": "GET"
    }
   ]
  },
  {
   "title": "BlueFS DB %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (ceph_daemon) (ceph_bluefs_db_used_bytes{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}/ceph_bluefs_db_total_bytes{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}*100)",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "BlueFS Slow DB %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (ceph_daemon) (100*ceph_bluefs_slow_used_bytes{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}/ceph_bluefs_slow_total_bytes{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  { "title": "LATENCY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "OSD Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "1000*sum(increase(ceph_osd_op_r_latency_sum{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_r_latency_count{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[1m])),1)",
     "legendFormat": "read"
    },
    {
     "expr": "1000*sum(increase(ceph_osd_op_w_latency_sum{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_w_latency_count{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[1m])),1)",
     "legendFormat": "write"
    },
    {
     "expr": "1000*sum(increase(ceph_osd_op_rw_latency_sum{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_rw_latency_count{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[1m])),1)",
     "legendFormat": "overwrite"
    }
   ]
  },
  {
   "title": "OSD Apply Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (ceph_daemon) (ceph_osd_apply_latency_ms{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "OSD Commit Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (ceph_daemon) (ceph_osd_commit_latency_ms{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  { "title": "OBJECTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Total Objects",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_pool_objects{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Objects Unfound / Degraded / Misplaced",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_num_objects_unfound{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Unfound"
    },
    {
     "expr": "sum(ceph_num_objects_degraded{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum(ceph_num_objects_misplaced{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Misplaced"
    }
   ]
  },
  {
   "title": "PGs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_pg_active{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(ceph_pg_clean{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Clean"
    },
    {
     "expr": "sum(ceph_pg_peering{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Peering"
    },
    {
     "expr": "sum(ceph_pg_degraded{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum(ceph_pg_stale{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Stale"
    },
    {
     "expr": "sum(ceph_unclean_pgs{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Unclean"
    },
    {
     "expr": "sum(ceph_pg_undersized{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Undersized"
    },
    {
     "expr": "sum(ceph_pg_incomplete{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Incomplete"
    },
    {
     "expr": "sum(ceph_pg_forced_backfill{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Forced Backfill"
    },
    {
     "expr": "sum(ceph_pg_inconsistent{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Inconsistent"
    },
    {
     "expr": "sum(ceph_pg_forced_recovery{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Forced Recovery"
    },
    {
     "expr": "sum(ceph_pg_creating{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Creating"
    },
    {
     "expr": "sum(ceph_pg_wait_backfill{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Wait Backfill"
    },
    {
     "expr": "sum(ceph_pg_deep{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Deep"
    },
    {
     "expr": "sum(ceph_pg_scrubbing{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Scrubbing"
    },
    {
     "expr": "sum(ceph_pg_recovering{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Recovering"
    },
    {
     "expr": "sum(ceph_pg_repair{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Repair"
    },
    {
     "expr": "sum(ceph_pg_down{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Down"
    },
    {
     "expr": "sum(ceph_pg_peered{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Peered"
    },
    {
     "expr": "sum(ceph_pg_backfill{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Backfill"
    },
    {
     "expr": "sum(ceph_pg_remapped{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Remapped"
    },
    {
     "expr": "sum(ceph_pg_backfill_toofull{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Backfill Toofull"
    }
   ]
  },
  {
   "title": "Faulty PGs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_pg_degraded{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum(ceph_pg_stale{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Stale"
    },
    {
     "expr": "sum(ceph_pg_undersized{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Undersized"
    }
   ]
  },
  {
   "title": "Recovery Operations",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_recovery_ops{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}[$interval]))",
     "legendFormat": "OPS"
    }
   ]
  },
  { "title": "OSD Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "OSD Storage Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (ceph_daemon) (ceph_osd_stat_bytes_used{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "OSD Used %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (ceph_daemon) (ceph_osd_stat_bytes_used{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}/ceph_osd_stat_bytes{kubernetes_cluster=~\"$cluster\",instance=~\"$instance\"}*100)",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  }
 ]
}