{
 "title": "Ceph RBD",
 "description": "Ceph RBDs overview.",
 "tags": [
  "ceph",
  "cluster",
  "rbd",
  "storage"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(ceph_health_status,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(ceph_health_status{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(ceph_rbd_write_ops{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[30s])))",
     "legendFormat": "Writes"
    },
    {
     "expr": "round(sum(irate(ceph_rbd_read_ops{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[30s])))",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Highest IOPS",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, (sort(sum by (image,pool) ((irate(ceph_rbd_write_ops{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[30s]) + on(image, pool, namespace) irate(ceph_rbd_read_ops{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[30s]))))))"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(ceph_rbd_write_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[30s])))",
     "legendFormat": "Write"
    },
    {
     "expr": "round(sum(irate(ceph_rbd_read_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[30s])))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Highest Throughput",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "topk(10, sort(sum by (pool, image) (irate(ceph_rbd_read_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[30s]) + irate(ceph_rbd_write_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[30s]))))"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(ceph_rbd_write_latency_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[30s])) / sum(irate(ceph_rbd_write_latency_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[30s])))",
     "legendFormat": "Write"
    },
    {
     "expr": "round(sum(irate(ceph_rbd_read_latency_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[30s])) / sum(irate(ceph_rbd_read_latency_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[30s])))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Highest Latency",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sum by (pool, image) (irate(ceph_rbd_write_latency_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[30s]) / clamp_min(irate(ceph_rbd_write_latency_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[30s]), 1) + irate(ceph_rbd_read_latency_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[30s]) / clamp_min(irate(ceph_rbd_read_latency_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[30s]), 1)))"
    }
   ]
  }
 ]
}