{
 "title": "Ceph RGW Buckets",
 "description": "Ceph RadosGW Buckets details.",
 "tags": [
  "ceph",
  "cluster",
  "rgw",
  "s3",
  "storage"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(radosgw_usage_bucket_bytes,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(radosgw_usage_bucket_bytes{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(radosgw_usage_bucket_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "bkt",
    "label": "S3 Bucket",
    "query": "label_values(radosgw_usage_ops_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"},bucket)"
   }
  ]
 },
 "panels": [
  {
   "title": "S3 bytes written in $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (kubernetes_namespace,kubernetes_service_name,kubernetes_cluster,bucket) (increase(radosgw_usage_bucket_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",bucket=~\"$bkt\"}[$interval]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{bucket}}"
    }
   ]
  },
  {
   "title": "Average Objects Sizes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,bucket) (radosgw_usage_bucket_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",bucket=~\"$bkt\"}/radosgw_usage_bucket_objects{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",bucket=~\"$bkt\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{bucket}}"
    }
   ]
  },
  {
   "title": "S3 Operations by Pod $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(radosgw_usage_ops_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",bucket=~\"$bkt\"}[$interval]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Total"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(radosgw_usage_successful_ops_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",bucket=~\"$bkt\"}[$interval]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Successful"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(radosgw_usage_successful_ops_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",bucket=~\"$bkt\"}[$interval]) - increase(radosgw_usage_ops_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",bucket=~\"$bkt\"}[$interval]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Failed"
    }
   ]
  },
  {
   "title": "S3 Operations breakdown per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,bucket,owner,category) (increase(radosgw_usage_ops_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",bucket=~\"$bkt\"}[$interval]))",
     "legendFormat": "Total {{owner}}@{{bucket}} {{category}}"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,bucket,owner,category) (increase(radosgw_usage_successful_ops_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",bucket=~\"$bkt\"}[$interval]))",
     "legendFormat": "Successfull {{owner}}@{{bucket}} {{category}}"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,bucket,owner,category) (increase(radosgw_usage_ops_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",bucket=~\"$bkt\"}[$interval]) - increase(radosgw_usage_successful_ops_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",bucket=~\"$bkt\"}[$interval]))",
     "legendFormat": "Failed {{owner}}@{{bucket}} {{category}}"
    }
   ]
  },
  {
   "title": "S3 TX/RX by Pod in $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(radosgw_usage_received_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",bucket=~\"$bkt\"}[$interval]))",
     "legendFormat": "RX {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(radosgw_usage_sent_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",bucket=~\"$bkt\"}[$interval]))",
     "legendFormat": "TX {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "S3 TX/RX breakdown in $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,bucket,owner,category) (increase(radosgw_usage_received_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",bucket=~\"$bkt\"}[$interval]))",
     "legendFormat": "RX {{kubernetes_namespace}}/{{kubernetes_service_name}} {{owner}}@{{bucket}} {{category}}"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,bucket,owner,category) (increase(radosgw_usage_sent_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",bucket=~\"$bkt\"}[$interval]))",
     "legendFormat": "TX {{kubernetes_namespace}}/{{kubernetes_service_name}} {{owner}}@{{bucket}} {{category}}"
    }
   ]
  }
 ]
}