{
 "title": "Docker Registry",
 "description": "Docker Registry overview.",
 "tags": [
  "docker",
  "registry"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(repository_tags_total,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(repository_tags_total{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "pod",
    "label": "Kubernetes Pod",
    "query": "label_values(repository_tags_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_pod_name)"
   },
   {
    "name": "repo",
    "label": "Docker Repository",
    "query": "label_values(repository_tags_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"},repository)"
   },
   { "name": "interval", "label": "Interval", "query": "30m,1h,6h,12h,1d,7d,14d,30d" }
  ]
 },
 "panels": [
  {
   "title": "Last Registry Restart",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Total Images",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(repository_revisions_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",repository=~\"$repo\"})"
    }
   ]
  },
  {
   "title": "Average Image Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(repository_tag_size_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",repository=~\"$repo\"})"
    }
   ]
  },
  {
   "title": "Revisions Pushed per $interval",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(repository_revisions_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",repository=~\"$repo\"}[$interval]))",
     "legendFormat": "Revisions Pushed"
    }
   ]
  },
  {
   "title": "Total Repositories",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(repository_revisions_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",repository=~\"$repo\"})"
    }
   ]
  },
  {
   "title": "Total Tags",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(repository_tags_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",repository=~\"$repo\"})"
    }
   ]
  },
  {
   "title": "Total Layers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(repository_tag_layers_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",repository=~\"$repo\"})"
    }
   ]
  },
  {
   "title": "Layers Pushed per $interval",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(repository_tag_layers_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",repository=~\"$repo\"}[$interval]))",
     "legendFormat": "New Layers"
    }
   ]
  },
  {
   "title": "Repositories with Most Tags",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(5,repository_tags_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",repository=~\"$repo\"}))",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Repositories with Most Images",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(5,repository_revisions_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",repository=~\"$repo\"}))",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Repositories with Largest Images",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(5,repository_tag_size_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",repository=~\"$repo\"}))",
     "legendFormat": "{{repository}}"
    }
   ]
  }
 ]
}