{
 "title": "HAProxy",
 "description": "HAProxy metrics overview.",
 "tags": [
  "front",
  "haproxy",
  "proxy"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,10m,30m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(haproxy_up,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(haproxy_up{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(haproxy_up{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "podname",
    "label": "Kubernetes Pod",
    "query": "label_values(haproxy_up{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"},kubernetes_pod_name)"
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": "label_values(haproxy_backend_bytes_in_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"},backend)"
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": "label_values(haproxy_frontend_bytes_in_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"},frontend)"
   },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(haproxy_server_bytes_in_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",backend=~\"$backend\"},server)"
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": "label_values(haproxy_server_http_responses_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",backend=~\"$backend\",server=~\"$server\"},code)"
   }
  ]
 },
 "panels": [
  { "title": "Basic Backend status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backends Up / Down",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(haproxy_backend_up{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"} == 1)",
     "legendFormat": "Backends Up"
    },
    {
     "expr": "count(haproxy_backend_up{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"} == 0)",
     "legendFormat": "Backends Down"
    }
   ]
  },
  { "title": "Basic General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total responses by HTTP code",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_http_responses_total{frontend=~\"$frontend\",code=~\"$code\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])) by (code)",
     "legendFormat": "Frontend {{ code }}"
    },
    {
     "expr": "sum(irate(haproxy_backend_http_responses_total{backend=~\"$backend\",code=~\"$code\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])) by (code)",
     "legendFormat": "Backend {{ code }}"
    }
   ]
  },
  {
   "title": "Current total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_bytes_in_total{frontend=~\"$frontend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} IN Front"
    },
    {
     "expr": "sum(irate(haproxy_frontend_bytes_out_total{frontend=~\"$frontend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} OUT Front"
    },
    {
     "expr": "sum(irate(haproxy_backend_bytes_in_total{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} IN Back"
    },
    {
     "expr": "sum(irate(haproxy_backend_bytes_out_total{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} OUT Back"
    }
   ]
  },
  {
   "title": "Total number of connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_connections_total{frontend=~\"$frontend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Front"
    },
    {
     "expr": "sum(irate(haproxy_backend_sessions_total{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Back"
    },
    {
     "expr": "sum(irate(haproxy_backend_connection_errors_total{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Back errors"
    }
   ]
  },
  {
   "title": "Total requests / responses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_http_requests_total{frontend=~\"$frontend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Requests"
    },
    {
     "expr": "sum(irate(haproxy_backend_response_errors_total{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Response errors"
    },
    {
     "expr": "sum(irate(haproxy_frontend_request_errors_total{frontend=~\"$frontend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Requests errors"
    },
    {
     "expr": "sum(irate(haproxy_backend_redispatch_warnings_total{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Backend redispatch"
    },
    {
     "expr": "sum(irate(haproxy_backend_retry_warnings_total{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Backend retry"
    },
    {
     "expr": "sum(irate(haproxy_frontend_requests_denied_total{frontend=~\"$frontend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Request denied"
    },
    {
     "expr": "sum(haproxy_backend_current_queue{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Backend Queued"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_frontend_current_sessions{frontend=~\"$frontend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Frontend current sessions"
    },
    {
     "expr": "sum(haproxy_frontend_current_session_rate{frontend=~\"$frontend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Frontend current session rate"
    },
    {
     "expr": "sum(haproxy_backend_current_sessions{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Backend current sessions"
    },
    {
     "expr": "sum(haproxy_backend_current_session_rate{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Backend current session rate"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Back - Current total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_bytes_in_total{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} IN-{{ backend }}"
    },
    {
     "expr": "irate(haproxy_backend_bytes_out_total{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} OUT-{{ backend }}"
    }
   ]
  },
  {
   "title": "Front - Current total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_bytes_in_total{frontend=~\"$frontend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} IN-{{ frontend }}"
    },
    {
     "expr": "irate(haproxy_frontend_bytes_out_total{frontend=~\"$frontend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} OUT-{{ frontend }}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Back - Total number of connections OK / Error",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_sessions_total{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }}"
    },
    {
     "expr": "irate(haproxy_backend_connection_errors_total{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }} Error"
    }
   ]
  },
  {
   "title": "Front - Total number of connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_connections_total{frontend=~\"$frontend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ frontend }}"
    }
   ]
  },
  { "title": "Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Back - Maximum observed number of queued requests not assigned to any server",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_max_queue{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }}"
    }
   ]
  },
  {
   "title": "Back - Current number of queued requests not assigned to any server",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_current_queue{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }}"
    }
   ]
  },
  { "title": "Requests / Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Back - Total of redispatch / error / retry warnings",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_redispatch_warnings_total{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Redispatch {{ backend }}"
    },
    {
     "expr": "irate(haproxy_backend_retry_warnings_total{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Retry {{ backend }}"
    },
    {
     "expr": "irate(haproxy_backend_response_errors_total{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Error {{ backend }}"
    }
   ]
  },
  {
   "title": "Front - Total HTTP requests OK / Error / Denied",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_http_requests_total{frontend=~\"$frontend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ frontend }}"
    },
    {
     "expr": "irate(haproxy_frontend_request_errors_total{frontend=~\"$frontend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ frontend }} Error"
    },
    {
     "expr": "irate(haproxy_frontend_requests_denied_total{frontend=~\"$frontend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ frontend }} Denied"
    }
   ]
  },
  { "title": "Responses by HTTP code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Back - Total of HTTP responses",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_http_responses_total{backend=~\"$backend\",code=~\"$code\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ code }} {{ backend }}"
    }
   ]
  },
  {
   "title": "Front - Total of HTTP responses",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_http_responses_total{frontend=~\"$frontend\",code=~\"$code\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ code }} {{ frontend }} "
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Back - Current number of active sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_current_sessions{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }}"
    }
   ]
  },
  {
   "title": "Front - Current number of active sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_frontend_current_sessions{frontend=~\"$frontend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ frontend }}"
    }
   ]
  },
  {
   "title": "Back - Current number of sessions rate per second over last elapsed second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_current_session_rate{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }}"
    }
   ]
  },
  {
   "title": "Front - Current number of sessions rate per second over last elapsed second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_frontend_current_session_rate{frontend=~\"$frontend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ frontend }}"
    }
   ]
  },
  {
   "title": "Back - Maximum observed number of active sessions and limit",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_max_sessions{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }}"
    },
    {
     "expr": "haproxy_backend_limit_sessions{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }} limit"
    }
   ]
  },
  {
   "title": "Front - Maximum observed number of active sessions and limit",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_frontend_max_sessions{frontend=~\"$frontend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ frontend }}"
    },
    {
     "expr": "haproxy_frontend_limit_sessions{frontend=~\"$frontend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ frontend }} limit"
    }
   ]
  },
  {
   "title": "Back - Maximum number of sessions rate per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_max_session_rate{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }}"
    }
   ]
  },
  {
   "title": "Front - Maximum number of sessions rate per second and limit",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_frontend_max_session_rate{frontend=~\"$frontend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ frontend }}"
    },
    {
     "expr": "haproxy_frontend_limit_session_rate{frontend=~\"$frontend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ frontend }} limit"
    }
   ]
  },
  { "title": "Health and Weight", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 } },
  {
   "title": "Back - Current health status of the backend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_up{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }}"
    }
   ]
  },
  {
   "title": "Back - Total weight of the servers in the backend / Active servers backend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 138 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_weight{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }}"
    }
   ]
  },
  { "title": "By Server Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } },
  {
   "title": "Server - Current total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 148 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_bytes_in_total{backend=~\"$backend\",server=~\"$server\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} IN-{{ backend }} / {{ server }}"
    },
    {
     "expr": "irate(haproxy_server_bytes_out_total{backend=~\"$backend\",server=~\"$server\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} OUT-{{ backend }} / {{ server }}"
    }
   ]
  },
  { "title": "By Server Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 163 } },
  {
   "title": "Server - Total number of sessions",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 164 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_sessions_total{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }} / {{ server }}"
    }
   ]
  },
  { "title": "By Server Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 176 } },
  {
   "title": "Server - Maximum observed number of queued requests assigned to this server",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 177 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_max_queue{backend=~\"$backend\",server=~\"$server\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Current number of queued requests assigned to this server",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 177 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_current_queue{backend=~\"$backend\",server=~\"$server\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }} / {{ server }}"
    }
   ]
  },
  { "title": "By Server Requests / Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 188 } },
  {
   "title": "Server - Total of HTTP responses OK",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 189 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_server_http_responses_total{backend=~\"$backend\",server=~\"$server\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])) by (server)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }} {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Total of retry / error / redispatch warnings",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 189 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_retry_warnings_total{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Retry {{ backend }} {{ server }}"
    },
    {
     "expr": "irate(haproxy_server_redispatch_warnings_total{backend=~\"$backend\",server=~\"$server\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Redispatch {{ backend }} {{ server }}"
    },
    {
     "expr": "irate(haproxy_server_response_errors_total{backend=~\"$backend\",server=~\"$server\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Error {{ backend }} {{ server }}"
    }
   ]
  },
  {
   "title": "By Server Responses by HTTP code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 202 }
  },
  {
   "title": "Server - Total of HTTP responses",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 203 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_http_responses_total{backend=~\"$backend\",server=~\"$server\",code=~\"$code\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }} {{ server }} {{ code }}"
    }
   ]
  },
  { "title": "By Server Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 214 } },
  {
   "title": "Server - Current number of active sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 215 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_current_sessions{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{{kubernetes_namespace}}/{{kubernetes_pod_name}} { backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Current number of sessions rate per second over last elapsed second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 215 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_current_session_rate{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Maximum observed number of sessions rate per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 225 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_max_session_rate{backend=~\"$backend\",server=~\"$server\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Maximum observed number of active sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 225 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_max_sessions{backend=~\"$backend\",server=~\"$server\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }} / {{ server }}"
    }
   ]
  },
  { "title": "By Server Health Weight", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 235 } },
  {
   "title": "Server - Total downtime in seconds",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 236 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_downtime_seconds_total{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Total number of failed health checks",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 236 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_server_check_failures_total{backend=~\"$backend\",server=~\"$server\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Total of connection errors",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 249 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_connection_errors_total{backend=~\"$backend\",server=~\"$server\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Previously run health check duration, in milliseconds",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 249 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_check_duration_seconds{backend=~\"$backend\",server=~\"$server\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Current health status of the server",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 262 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_up{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Current weight of the server",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 262 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_weight{backend=~\"$backend\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{ backend }} / {{ server }}"
    }
   ]
  },
  { "title": "Scrape info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 275 } },
  {
   "title": "Number of errors while parsing CSV",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 276 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_exporter_csv_parse_failures_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Exporter csv failures"
    }
   ]
  },
  {
   "title": "Current total HAProxy scrapes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 276 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_exporter_scrapes_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} HAProxy scrapes"
    }
   ]
  }
 ]
}