{
 "title": "Kubernetes Networking Details",
 "description": "Kubernetes Networking Detailed overview.",
 "tags": [
  "cluster",
  "kubernetes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(container_network_receive_packets_total,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(container_network_receive_packets_total{kubernetes_cluster=~\"$cluster\"},namespace)"
   },
   { "name": "resolution", "query": "30s,5m,1h" },
   { "name": "interval", "query": "1h,2h,4h,6h,12h,1d" }
  ]
 },
 "panels": [
  { "title": "Current Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Rate of Bytes Received",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "format": "time_series",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution]))"
    }
   ]
  },
  {
   "title": "Current Rate of Bytes Transmitted",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "format": "time_series",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution]))"
    }
   ]
  },
  {
   "title": "Current Status",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace,pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace,pod)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace,pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace,pod)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace,pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace,pod)"
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace,pod)",
     "legendFormat": "{{kubernetes_cluster}}/{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace,pod)",
     "legendFormat": "{{kubernetes_cluster}}/{{namespace}}/{{pod}}"
    }
   ]
  },
  { "title": "Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Rate of Received Packets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace,pod)",
     "legendFormat": "{{kubernetes_cluster}}/{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace,pod)",
     "legendFormat": "{{kubernetes_cluster}}/{{namespace}}/{{pod}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace,pod)",
     "legendFormat": "{{kubernetes_cluster}}/{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace,pod)",
     "legendFormat": "{{kubernetes_cluster}}/{{namespace}}/{{pod}}"
    }
   ]
  }
 ]
}