{
 "title": "Kubernetes Networking",
 "description": "Kubernetes Networking overview.",
 "tags": [
  "cluster",
  "kubernetes"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(container_network_receive_bytes_total,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(container_network_receive_bytes_total{kubernetes_cluster=~\"$cluster\"},namespace)"
   },
   {
    "name": "pod",
    "label": "Pod Name",
    "query": "label_values(container_network_receive_bytes_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"},pod)"
   },
   { "name": "resolution", "query": "30s,5m,1h" },
   { "name": "interval", "query": "1h,2h,4h,6h,12h" }
  ]
 },
 "panels": [
  { "title": "Current Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Rate of Bytes Received per Namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_receive_bytes_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace))",
     "legendFormat": "{{kubernetes_cluster}}/{{namespace}}"
    }
   ]
  },
  {
   "title": "Current Rate of Bytes Transmitted per Namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_bytes_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace))",
     "legendFormat": "{{kubernetes_cluster}}/{{namespace}}"
    }
   ]
  },
  {
   "title": "Breakdown per Namespace",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_receive_bytes_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace))"
    },
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_bytes_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace))"
    },
    {
     "expr": "sort_desc(avg(irate(container_network_receive_bytes_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace))"
    },
    {
     "expr": "sort_desc(avg(irate(container_network_transmit_bytes_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace))"
    },
    {
     "expr": "sort_desc(sum(irate(container_network_receive_packets_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace))"
    },
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_packets_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace))"
    },
    {
     "expr": "sort_desc(sum(irate(container_network_receive_packets_dropped_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace))"
    },
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_packets_dropped_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace))"
    }
   ]
  },
  { "title": "Average Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Average Rate of Bytes Received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(avg(irate(container_network_receive_bytes_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace))",
     "legendFormat": "{{kubernetes_cluster}}/{{namespace}}"
    }
   ]
  },
  {
   "title": "Average Rate of Bytes Transmitted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(avg(irate(container_network_transmit_bytes_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace))",
     "legendFormat": "{{kubernetes_cluster}}/{{namespace}}"
    }
   ]
  },
  { "title": "Bandwidth History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "RX Bandwidth usage per Namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_receive_bytes_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace))",
     "legendFormat": "{{kubernetes_cluster}}/{{namespace}}"
    }
   ]
  },
  {
   "title": "TX Bandwidth usage per Namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_bytes_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace))",
     "legendFormat": "{{kubernetes_cluster}}/{{namespace}}"
    }
   ]
  },
  { "title": "Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Rate of Received Packets per Namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_receive_packets_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace))",
     "legendFormat": "{{kubernetes_cluster}}/{{namespace}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets per Namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_packets_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace))",
     "legendFormat": "{{kubernetes_cluster}}/{{namespace}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Rate of Received Packets Dropped per Namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_receive_packets_dropped_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace))",
     "legendFormat": "{{kubernetes_cluster}}/{{namespace}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped per Namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_packets_dropped_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (kubernetes_cluster,namespace))",
     "legendFormat": "{{kubernetes_cluster}}/{{namespace}}"
    }
   ]
  },
  {
   "title": "Rate of TCP Retransmits out of all sent segments",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(node_netstat_Tcp_RetransSegs{kubernetes_cluster=~\"$cluster\"}[$interval:$resolution]) / rate(node_netstat_Tcp_OutSegs{kubernetes_cluster=~\"$cluster\"}[$interval:$resolution])) by (kubernetes_cluster,kubernetes_node_name))",
     "legendFormat": "{{kubernetes_cluster}}/{{kubernetes_node_name}}"
    }
   ]
  },
  {
   "title": "Rate of TCP SYN Retransmits out of all retransmits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(node_netstat_TcpExt_TCPSynRetrans{kubernetes_cluster=~\"$cluster\"}[$interval:$resolution]) / rate(node_netstat_Tcp_RetransSegs{kubernetes_cluster=~\"$cluster\"}[$interval:$resolution])) by (kubernetes_cluster,kubernetes_node_name))",
     "legendFormat": "{{kubernetes_cluster}}/{{kubernetes_node_name}}"
    }
   ]
  }
 ]
}