{
 "title": "Kubernetes Kubelet",
 "description": "Kubernetes Kubelet overview.",
 "tags": [
  "cluster",
  "kubernetes"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(kube_pod_info,kubernetes_cluster)"
   },
   {
    "name": "instance",
    "label": "Kubernetes Node",
    "query": "label_values(kubelet_runtime_operations_total{kubernetes_cluster=\"$cluster\",job=\"kubelet\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{kubernetes_cluster=~\"$cluster\",job=\"kubelet\"})"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_pod_count{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Running Container",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_container_count{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Actual Volume Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(volume_manager_total_volumes{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\",state=\"actual_state_of_world\"})"
    }
   ]
  },
  {
   "title": "Desired Volume Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(volume_manager_total_volumes{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\",state=\"desired_state_of_world\"})"
    }
   ]
  },
  {
   "title": "Config Error Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_node_config_error{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Operation Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_total{kubernetes_cluster=\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}[5m])) by (kubernetes_cluster,operation_type,instance)",
     "legendFormat": "{{kubernetes_cluster}}/{{instance}} {{operation_type}}"
    }
   ]
  },
  {
   "title": "Operation Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_errors_total{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}[5m])) by (kubernetes_cluster,instance,operation_type)",
     "legendFormat": "{{kubernetes_cluster}}/{{instance}} {{operation_type}}"
    }
   ]
  },
  {
   "title": "Operation duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_runtime_operations_duration_seconds_bucket{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}[5m])) by (kubernetes_cluster,instance,operation_type,le))",
     "legendFormat": "{{kubernetes_cluster}}/{{instance}} {{operation_type}}"
    }
   ]
  },
  {
   "title": "Pod Start Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_pod_start_duration_seconds_count{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}[5m])) by (kubernetes_cluster,instance)",
     "legendFormat": "{{kubernetes_cluster}}/{{instance}} pod"
    },
    {
     "expr": "sum(rate(kubelet_pod_worker_duration_seconds_count{kubernetes_cluster=\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}[5m])) by (kubernetes_cluster,instance)",
     "legendFormat": "{{kubernetes_cluster}}/{{instance}} worker"
    }
   ]
  },
  {
   "title": "Pod Start Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_pod_start_duration_seconds_count{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}[5m])) by (kubernetes_cluster,instance,le))",
     "legendFormat": "{{kubernetes_cluster}}/{{instance}} pod"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_pod_worker_duration_seconds_bucket{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}[5m])) by (kubernetes_cluster,instance,le))",
     "legendFormat": "{{kubernetes_cluster}}/{{instance}} worker"
    }
   ]
  },
  {
   "title": "Storage Operation Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storage_operation_duration_seconds_count{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}[5m])) by (kubernetes_cluster,instance,operation_name,volume_plugin)",
     "legendFormat": "{{kubernetes_cluster}}/{{instance}} {{operation_name}} {{volume_plugin}}"
    }
   ]
  },
  {
   "title": "Storage Operation Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storage_operation_errors_total{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}[5m])) by (kubernetes_cluster,instance,operation_name,volume_plugin)",
     "legendFormat": "{{kubernetes_cluster}}/{{instance}} {{operation_name}} {{volume_plugin}}"
    }
   ]
  },
  {
   "title": "Storage Operation Duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(storage_operation_duration_seconds_bucket{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}[5m])) by (kubernetes_cluster,instance,operation_name,volume_plugin,le))",
     "legendFormat": "{{kubernetes_cluster}}/{{instance}} {{operation_name}} {{volume_plugin}}"
    }
   ]
  },
  {
   "title": "Cgroup manager operation rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_cgroup_manager_duration_seconds_count{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}[5m])) by (kubernetes_cluster,instance, operation_type)",
     "legendFormat": "{{kubernetes_cluster}}/{{instance}} {{operation_type}}"
    }
   ]
  },
  {
   "title": "Cgroup manager 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_cgroup_manager_duration_seconds_bucket{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}[5m])) by (kubernetes_cluster,instance,operation_type,le))",
     "legendFormat": "{{kubernetes_cluster}}/{{instance}} {{operation_type}}"
    }
   ]
  },
  {
   "title": "PLEG relist rate",
   "type": "graph",
   "description": "Pod lifecycle event generator",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_pleg_relist_duration_seconds_count{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}[5m])) by (kubernetes_cluster,instance)",
     "legendFormat": "{{kubernetes_cluster}}/{{instance}}"
    }
   ]
  },
  {
   "title": "PLEG relist interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_pleg_relist_interval_seconds_bucket{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}[5m])) by (instance,kubernetes_cluster,le))",
     "legendFormat": "{{kubernetes_cluster}}/{{instance}}"
    }
   ]
  },
  {
   "title": "PLEG relist duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_pleg_relist_duration_seconds_bucket{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}[5m])) by (instance,le,kubernetes_cluster))",
     "legendFormat": "{{kubernetes_cluster}}/{{instance}}"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\",code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\",code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\",code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\",code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_latency_seconds_bucket{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$instance\"}[5m])) by (kubernetes_node_name,verb,url,le,kubernetes_cluster))",
     "legendFormat": "{{kubernetes_cluster}}/{{kubernetes_node_name}} {{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}",
     "legendFormat": "{{kubernetes_cluster}}/{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{kubernetes_cluster}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_cluster=~\"$cluster\",job=\"kubelet\",instance=~\"$instance\"}",
     "legendFormat": "{{kubernetes_cluster}}/{{instance}}"
    }
   ]
  }
 ]
}