{
 "title": "Kubernetes Capacity Planning",
 "description": "Kubernetes Capacity Planning.",
 "tags": [
  "cluster",
  "kubernetes"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(kube_node_info,kubernetes_cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Idle CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{kubernetes_cluster=~\"$cluster\",mode=\"idle\"}[2m]))"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1{kubernetes_cluster=~\"$cluster\"})",
     "legendFormat": "load 1m sum"
    },
    {
     "expr": "sum(node_load5{kubernetes_cluster=~\"$cluster\"})",
     "legendFormat": "load 5m sum"
    },
    {
     "expr": "sum(node_load15{kubernetes_cluster=~\"$cluster\"})",
     "legendFormat": "load 15m sum"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{kubernetes_cluster=~\"$cluster\"}) - sum(node_memory_MemFree_bytes{kubernetes_cluster=~\"$cluster\"}) - sum(node_memory_Buffers_bytes{kubernetes_cluster=~\"$cluster\"}) - sum(node_memory_Cached_bytes{kubernetes_cluster=~\"$cluster\"})",
     "legendFormat": "Global Usage"
    },
    {
     "expr": "sum(node_memory_Buffers_bytes{kubernetes_cluster=~\"$cluster\"})",
     "legendFormat": "Buffers"
    },
    {
     "expr": "sum(node_memory_Cached_bytes{kubernetes_cluster=~\"$cluster\"})",
     "legendFormat": "Cached"
    },
    {
     "expr": "sum(node_memory_MemFree_bytes{kubernetes_cluster=~\"$cluster\"})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal_bytes{kubernetes_cluster=~\"$cluster\"}) - sum(node_memory_MemFree_bytes{kubernetes_cluster=~\"$cluster\"}) - sum(node_memory_Buffers_bytes{kubernetes_cluster=~\"$cluster\"}) - sum(node_memory_Cached_bytes{kubernetes_cluster=~\"$cluster\"})) / sum(node_memory_MemTotal_bytes{kubernetes_cluster=~\"$cluster\"})) * 100"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{kubernetes_cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{kubernetes_cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "Written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total{kubernetes_cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "IO Times"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{kubernetes_cluster=~\"$cluster\"}) - sum(node_filesystem_free_bytes{kubernetes_cluster=~\"$cluster\"})) / sum(node_filesystem_size_bytes{kubernetes_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{kubernetes_cluster=~\"$cluster\",device!~\"lo\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{kubernetes_cluster=~\"$cluster\",device!~\"lo\"}[5m]))"
    }
   ]
  },
  {
   "title": "Cluster Pod Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_info{kubernetes_cluster=~\"$cluster\"})",
     "legendFormat": "Current number of Pods"
    },
    {
     "expr": "sum(kube_node_status_capacity_pods{kubernetes_cluster=~\"$cluster\"})",
     "legendFormat": "Maximum capacity of pods"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods{kubernetes_cluster=~\"$cluster\"}) - sum(kube_pod_info{kubernetes_cluster=~\"$cluster\"})) / sum(kube_node_status_capacity_pods{kubernetes_cluster=~\"$cluster\"}) * 100"
    }
   ]
  }
 ]
}