{
 "title": "Kubernetes Pods",
 "description": "Kubernetes Pods metrics overview.",
 "tags": [
  "cluster",
  "kubernetes"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(kube_pod_info,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(kube_pod_info{kubernetes_cluster=~\"$cluster\"},namespace)"
   },
   {
    "name": "pod",
    "label": "Pod Name",
    "query": "label_values(kube_pod_info{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"},pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"},container)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,namespace,pod,container) (container_memory_usage_bytes{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container=~\".+\"})",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}} Consumed"
    },
    {
     "expr": "sum by (kubernetes_cluster,namespace,pod,container) (kube_pod_container_resource_requests_memory_bytes{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\"})",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}} Requested"
    },
    {
     "expr": "sum by (kubernetes_cluster,namespace,pod,container) (kube_pod_container_resource_limits_memory_bytes{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\"})",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}} Limit"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,namespace,pod,container) (kube_pod_container_resource_requests_cpu_cores{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\"})",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}} Requested"
    },
    {
     "expr": "sum by (kubernetes_cluster,namespace,pod,container) (rate(container_cpu_usage_seconds_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container=~\".+\"}[1m]))",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}} Consumed"
    },
    {
     "expr": "sum by (kubernetes_cluster,namespace,pod,container) (kube_pod_container_resource_limits_cpu_cores{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\"})",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}} Limit"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (kubernetes_cluster,namespace,pod,pod_name,interface) (rate(container_network_receive_bytes_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\",pod_name=~\"$pod\"}[1m])) or sum by (kubernetes_cluster,namespace,pod,pod_name,interface) (rate(container_network_receive_bytes_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m]))) ",
     "legendFormat": "RX {{namespace}}/{{pod}}{{pod_name}} {{interface}}"
    },
    {
     "expr": "sort_desc(sum by (kubernetes_cluster,namespace,pod,pod_name,interface) (rate(container_network_transmit_bytes_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\",pod_name=~\"$pod\"}[1m])) or sum by (kubernetes_cluster,namespace,pod,pod_name,interface) (rate(container_network_transmit_bytes_total{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m]))) ",
     "legendFormat": "TX {{namespace}}/{{pod}}{{pod_name}} {{interface}}"
    }
   ]
  }
 ]
}