{
 "title": "Kubernetes Clusters Health",
 "description": "Kubernetes Cluster Health overview.",
 "tags": [
  "cluster",
  "kubernetes"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(kube_node_status_condition,kubernetes_cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Control Plane Components Down",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{kubernetes_cluster=~\"$cluster\",pod=~\"kube-apiserver.*|kube-scheduler.*|kube-controller.*\",namespace=\"kube-system\"} == 0)"
    }
   ]
  },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{kubernetes_cluster=~\"$cluster\",alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Alerts Pending",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{kubernetes_cluster=~\"$cluster\",alertstate=\"pending\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Crashlooping Pods",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts{kubernetes_cluster=~\"$cluster\"}[1h]) > 5)"
    }
   ]
  },
  {
   "title": "Node Not Ready",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{kubernetes_cluster=~\"$cluster\",condition=\"Ready\",status!=\"true\"})"
    }
   ]
  },
  {
   "title": "Node Disk Pressure",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{kubernetes_cluster=~\"$cluster\",condition=\"DiskPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Node Memory Pressure",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{kubernetes_cluster=~\"$cluster\",condition=\"MemoryPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unschedulable",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{kubernetes_cluster=~\"$cluster\"})"
    }
   ]
  }
 ]
}