{
 "title": "Kubernetes Backups",
 "description": "Kubernetes Backups overview.",
 "tags": [
  "backups",
  "kubernetes"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(backup_job_last_successful_timestamp_seconds,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(backup_job_last_successful_timestamp_seconds{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(backup_job_last_successful_timestamp_seconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "jobname",
    "label": "Job Name",
    "query": "label_values(backup_job_last_successful_timestamp_seconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"},jobname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Filesystem Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * backup_filesystem_free_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"} / backup_filesystem_total_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"}",
     "legendFormat": "Space Free"
    }
   ]
  },
  {
   "title": "Top Successes",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 20, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5, backup_job_successful_count_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",jobname=~\"$jobname\"} > 0)",
     "legendFormat": "{{kubernetes_namespace}}/{{jobname}}"
    }
   ]
  },
  {
   "title": "Jobs with Failures",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 20, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bottomk(5, backup_job_failed_count_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",jobname=~\"$jobname\"} > 0)",
     "legendFormat": "{{kubernetes_namespace}}/{{jobname}}"
    }
   ]
  },
  {
   "title": "Inodes Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * backup_filesystem_free_inodes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"} / backup_filesystem_total_inodes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"}",
     "legendFormat": "Inodes Free"
    }
   ]
  },
  {
   "title": "Time Since Last Failed Backup",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(6, (time() - (backup_job_last_failed_timestamp_seconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",jobname=~\"$jobname\"} > 0)))",
     "legendFormat": "{{kubernetes_namespace}}/{{jobname}}"
    }
   ]
  },
  {
   "title": "Time Since Last Successful Backup",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(6, (time() - (backup_job_last_successful_timestamp_seconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",jobname=~\"$jobname\"} > 0)))",
     "legendFormat": "{{kubernetes_namespace}}/{{jobname}}"
    }
   ]
  }
 ]
}