{
 "title": "Kubernetes Clusters Status",
 "description": "Kubernetes Cluster Status overview.",
 "tags": [
  "cluster",
  "kubernetes"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(node_cpu_seconds_total,kubernetes_cluster)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Control Plane UP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{kubernetes_cluster=~\"$cluster\",pod=~\"kube-apiserver.*|kube-controller.*|kube-scheduler.*\",namespace=\"kube-system\"} == 0)"
    }
   ]
  },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{kubernetes_cluster=~\"$cluster\",alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  { "title": "Control Plane Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "API Servers UP",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_pod_container_status_ready{kubernetes_cluster=~\"$cluster\",pod=~\"kube-apiserver.*\",namespace=\"kube-system\"} == 1) / count(kube_pod_container_status_ready{kubernetes_cluster=~\"$cluster\",pod=~\"kube-apiserver.*\",namespace=\"kube-system\"})) * 100"
    }
   ]
  },
  {
   "title": "Controller Managers UP",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_pod_container_status_ready{kubernetes_cluster=~\"$cluster\",pod=~\"kube-controller.*\",namespace=\"kube-system\"} == 1) / count(kube_pod_container_status_ready{kubernetes_cluster=~\"$cluster\",pod=~\"kube-controller.*\",namespace=\"kube-system\"})) * 100"
    }
   ]
  },
  {
   "title": "Schedulers UP",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_pod_container_status_ready{kubernetes_cluster=~\"$cluster\",pod=~\"kube-scheduler.*\",namespace=\"kube-system\"} == 1) / count(kube_pod_container_status_ready{kubernetes_cluster=~\"$cluster\",pod=~\"kube-scheduler.*\",namespace=\"kube-system\"})) * 100"
    }
   ]
  },
  {
   "title": "Crashlooping Control Plane Pods",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts{kubernetes_cluster=~\"$cluster\",namespace=~\"kube-system\"}[1h]) > 5)"
    }
   ]
  },
  { "title": "Capacity Planning", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(100 - (avg by (kubernetes_cluster,kubernetes_node_name) (rate(node_cpu_seconds_total{kubernetes_cluster=~\"$cluster\",mode=\"idle\"}[5m])) * 100)) / count(node_cpu_seconds_total{kubernetes_cluster=~\"$cluster\",mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal_bytes{kubernetes_cluster=~\"$cluster\"}) - sum(node_memory_MemFree_bytes{kubernetes_cluster=~\"$cluster\"}) - sum(node_memory_Buffers_bytes{kubernetes_cluster=~\"$cluster\"}) - sum(node_memory_Cached_bytes{kubernetes_cluster=~\"$cluster\"})) / sum(node_memory_MemTotal_bytes{kubernetes_cluster=~\"$cluster\"})) * 100"
    }
   ]
  },
  {
   "title": "Filesystem Utilization",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{kubernetes_cluster=~\"$cluster\",device!=\"rootfs\"}) - sum(node_filesystem_free_bytes{kubernetes_cluster=~\"$cluster\",device!=\"rootfs\"})) / sum(node_filesystem_size_bytes{kubernetes_cluster=~\"$cluster\",device!=\"rootfs\"}) * 100"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods{kubernetes_cluster=~\"$cluster\"}) - sum(kube_pod_info{kubernetes_cluster=~\"$cluster\"})) / sum(kube_node_status_capacity_pods{kubernetes_cluster=~\"$cluster\"}) * 100"
    }
   ]
  }
 ]
}