{
 "title": "Mattermost Bonus",
 "description": "Mattermost Performance metrics (bonus).",
 "tags": [
  "application",
  "mattermost",
  "go"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(mattermost_login_logins_total{},kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(mattermost_login_logins_total{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(mattermost_login_logins_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "pod",
    "label": "Pod Name",
    "query": "label_values(mattermost_login_logins_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Successful Logins / Number of Login Attempts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "Login Success Rate" }
   ],
   "targets": [
    {
     "expr": "mattermost_login_logins_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}/(mattermost_login_logins_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}+mattermost_login_logins_fail_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(mattermost_login_logins_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})/(sum(mattermost_login_logins_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})+sum(mattermost_login_logins_fail_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Number of Successful Logins per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_login_logins_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[1m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(irate(mattermost_login_logins_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of Emails Sent per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_post_emails_sent_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[1m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(irate(mattermost_post_emails_sent_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of Mobile Push Notifications Sent per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_post_pushes_sent_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[1m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(irate(mattermost_post_pushes_sent_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of File Attachments per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_post_file_attachments_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[1m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(irate(mattermost_post_file_attachments_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of Search Queries for Posts per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_search_posts_searches_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[1m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(irate(mattermost_search_posts_searches_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Mean Search Query Time for Posts (in milliseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds (ms)" }
   ],
   "targets": [
    {
     "expr": "1000.0 * rate(mattermost_search_posts_searches_duration_seconds_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[1m]) / rate(mattermost_search_posts_searches_duration_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[1m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Number of Websocket Events per Second",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_websocket_event_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Number of Websocket Broadcasts per Second",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_websocket_broadcasts_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Number of API Requests per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_http_requests_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[1m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(irate(mattermost_http_requests_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of Cluster Requests per Second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_cluster_cluster_requests_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[1m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(irate(mattermost_cluster_cluster_requests_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of Cluster Events per Second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_cluster_cluster_event_type_totals{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Duration by Quantile (in seconds)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{quantile}}"
    }
   ]
  },
  {
   "title": "Number of Objects on the Heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_objects{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(go_memstats_heap_objects{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Etag Hit Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "percentunit", "label": "Hit Rate" }
   ],
   "targets": [
    {
     "expr": "mattermost_cache_etag_hit_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}/(mattermost_cache_etag_miss_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"} + mattermost_cache_etag_hit_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Memory Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "percentunit", "label": "Hit Rate" }
   ],
   "targets": [
    {
     "expr": "mattermost_cache_mem_hit_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}/(mattermost_cache_mem_miss_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"} + mattermost_cache_mem_hit_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Mean Etag Hit Rate (for each server)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 150 },
   "yaxes": [
    { "format": "percentunit", "label": "Hit Rate" }
   ],
   "targets": [
    {
     "expr": "mattermost_cache_etag_hit_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}/(mattermost_cache_etag_miss_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"} + mattermost_cache_etag_hit_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Mean Memory Cache Hit Rate (for each server)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 159 },
   "yaxes": [
    { "format": "percentunit", "label": "Hit Rate" }
   ],
   "targets": [
    {
     "expr": "mattermost_cache_mem_hit_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}/(mattermost_cache_mem_miss_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"} + mattermost_cache_mem_hit_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Resident Memory Size (in MB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 171 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "mattermost_process_resident_memory_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}/1024/1024",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(mattermost_process_resident_memory_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}/1024/1024)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Virtual Memory Size (in MB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 180 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "mattermost_process_virtual_memory_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}/1024/1024",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(mattermost_process_virtual_memory_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}/1024/1024)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 189 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "mattermost_process_open_fds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(mattermost_process_open_fds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}