{
 "title": "Memcached",
 "description": "Memcached metrics overview.",
 "tags": [
  "database",
  "nosgbd",
  "memcached"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(memcached_up,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(memcached_up{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(memcached_up{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "pod",
    "label": "Pod Name",
    "query": "label_values(memcached_up{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(memcached_current_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}) / sum(memcached_limit_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Hit rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (irate (memcached_commands_total{status=\"hit\",command=\"get\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}[5m])) / sum (irate (memcached_commands_total{command=\"get\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Hit"
    }
   ]
  },
  {
   "title": "Evicts & Reclaims rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate (memcached_items_evicted_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "evicts"
    },
    {
     "expr": "sum (irate (memcached_items_reclaimed_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "reclaims"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (memcached_current_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\", kubernetes_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (memcached_limit_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\", kubernetes_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Hit & Miss ratio",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_commands_total{status=\"hit\",command=\"get\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}) / sum (memcached_commands_total{command=\"get\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "hit"
    },
    {
     "expr": "sum (memcached_commands_total{status=\"miss\",command=\"get\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}) / sum (memcached_commands_total{command=\"get\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Evicts (total)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (memcached_items_evicted_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\", kubernetes_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Reclaims (total)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (memcached_items_reclaimed_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\", kubernetes_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Items in cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_current_items{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (irate (memcached_read_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum (irate (memcached_written_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "written"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_current_connections{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Get & Set ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_commands_total{command=\"get\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}) / (sum (memcached_commands_total{command=\"get\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}) + sum (memcached_commands_total{command=\"set\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}))",
     "legendFormat": "Get"
    },
    {
     "expr": "sum (memcached_commands_total{command=\"set\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"})  / (sum (memcached_commands_total{command=\"get\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}) + sum (memcached_commands_total{command=\"set\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}))",
     "legendFormat": "Set"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate (memcached_commands_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}[5m])) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  }
 ]
}