{
 "title": "MinIO",
 "description": "MinIO overview.",
 "tags": [
  "cluster",
  "minio",
  "storage"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(minio_version_info,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(minio_version_info{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(minio_version_info{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "pod",
    "label": "Kubernetes Pod",
    "query": "label_values(minio_version_info{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://min.io/resources/img/logo/MINIO_wordmark.png\" style=\"height: 55px;\"></img>"
   },
   "content": "<img src=\"https://min.io/resources/img/logo/MINIO_wordmark.png\" style=\"height: 55px;\"></img>"
  },
  {
   "title": "Last Restart",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "MinIO Drives Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(minio_disks_offline{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "Offlines"
    },
    {
     "expr": "sum(minio_disks_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Storage Usage Breakdown",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * disk_storage_used{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"} / disk_storage_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{disk}}"
    }
   ]
  },
  {
   "title": "Total Storage Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(disk_storage_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Used Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(disk_storage_used{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Internode TX/RX in $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(internode_tx_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} TX"
    },
    {
     "expr": "rate(internode_rx_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} RX"
    }
   ]
  },
  {
   "title": "S3 TX/RX in $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "rate(s3_rx_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Received: "
    },
    {
     "expr": "rate(s3_tx_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Transmited:"
    }
   ]
  },
  {
   "title": "S3 Requests Breakdown (total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (api) (s3_requests_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "S3 Requests Breakdown (current)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(s3_requests_current{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "HTTP Requests by code in $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promhttp_metric_handler_requests_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Go Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Allocated by $interval"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Stack Used"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Heap Used"
    }
   ]
  },
  {
   "title": "CPU Usage by $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}