{
 "title": "MongoDB ReplSet",
 "description": "MongoDB ReplicaSet metrics overview.",
 "tags": [
  "cluster",
  "database",
  "mongodb",
  "replset",
  "nosgbd"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(mongodb_mongod_replset_my_state,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(mongodb_mongod_replset_my_state{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(mongodb_mongod_replset_my_state{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "replset",
    "label": "Replica Set",
    "query": "label_values(mongodb_mongod_replset_my_state{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"},set)"
   },
   {
    "name": "host",
    "label": "Pod Name",
    "query": "label_values(mongodb_mongod_replset_my_state{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",set=~\"$replset\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "ReplSet State",
   "type": "singlestat",
   "description": "Shows the role of the selected member instance (PRIMARY or SECONDARY)",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(mongodb_mongod_replset_my_state{kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"})"
    }
   ]
  },
  {
   "title": "ReplSet Members",
   "type": "singlestat",
   "description": "Shows the number of members in the replica set",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mongodb_mongod_replset_number_of_members{kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"})"
    }
   ]
  },
  {
   "title": "ReplSet Last Election",
   "type": "singlestat",
   "description": "Shows how long ago the last election occurred",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(mongodb_mongod_replset_member_election_date{kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"})"
    }
   ]
  },
  {
   "title": "ReplSet Lag",
   "type": "singlestat",
   "description": "Shows the current replication lag for the selected member",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(mongodb_mongod_replset_member_optime_date{state=\"PRIMARY\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}) - (min(mongodb_mongod_replset_member_optime_date{state=\"SECONDARY\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}) OR on() max(mongodb_mongod_replset_member_optime_date{state=\"PRIMARY\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}))"
    }
   ]
  },
  {
   "title": "Storage Engine",
   "type": "singlestat",
   "description": "Shows the storage engine used on the instance",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "count (mongodb_mongod_storage_engine{kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$host\"}) by (engine)",
     "legendFormat": "{{engine}}"
    }
   ]
  },
  {
   "title": "Replication Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,type) (rate(mongodb_mongod_op_counters_repl_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",set=~\"$replset\",kubernetes_pod_name=~\"$host\",type!~\"(command|getmore|query)\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",set=~\"$replset\",kubernetes_pod_name=~\"$host\",type!~\"(command|getmore|query)\"}[5m]) or rate(mongodb_op_counters_repl_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",set=~\"$replset\",kubernetes_pod_name=~\"$host\",type!~\"(command|getmore|query)\"}[$interval]) or irate(mongodb_op_counters_repl_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",set=~\"$replset\",kubernetes_pod_name=~\"$host\",type!~\"(command|getmore|query)\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{type}}"
    }
   ]
  },
  {
   "title": "Oplog Recovery Window",
   "type": "graph",
   "description": "Shows the time range in the oplog and the oldest backed up operation.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (time() - mongodb_mongod_replset_oplog_tail_timestamp{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",set=~\"$replset\",kubernetes_pod_name=~\"$host\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Now to End"
    },
    {
     "expr": "sum by (kubuernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (mongodb_mongod_replset_oplog_head_timestamp{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",set=~\"$replset\",kubernetes_pod_name=~\"$host\"} - mongodb_mongod_replset_oplog_tail_timestamp{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",set=~\"$replset\",kubernetes_pod_name=~\"$host\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Oplog Range"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "graph",
   "description": "Shows the delay between an operation occurring on the primary and that same operation getting applied on the selected member",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (max(mongodb_mongod_replset_member_optime_date{state=\"PRIMARY\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}) - min(mongodb_mongod_replset_member_optime_date{state=\"SECONDARY\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",set=~\"$replset\",kubernetes_pod_name=~\"$host\"} * on (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,kubernetes_pod_name,set) group_left mongodb_mongod_replset_my_name{kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",set=~\"$replset\",kubernetes_pod_name=~\"$host\"})) or vector(0)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Lag"
    }
   ]
  },
  {
   "title": "Elections",
   "type": "graph",
   "description": "Elections happen when a primary becomes unavailable. Look at this graph over longer periods (weeks or months) to determine patterns and correlate elections with other events.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(changes(mongodb_mongod_replset_member_election_date{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}[$interval]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Member State Uptime",
   "type": "graph",
   "description": "Shows how long various members were in PRIMARY and SECONDARY roles",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_uptime{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"} * on (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,kubernetes_pod_name,name) group_right(state) (max_over_time(mongodb_mongod_replset_my_name{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}[$interval]) or max_over_time(mongodb_mongod_replset_my_name{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} - {{state}}"
    }
   ]
  },
  {
   "title": "Max Heartbeat Time",
   "type": "graph",
   "description": "Shows the heartbeat return times sent by the current member to other members in the replica set.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - max(mongodb_mongod_replset_member_last_heartbeat{kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$host\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",set=~\"$replset\"}) by (name) * on (name) group_right mongodb_mongod_replset_my_name",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Max Member Ping Time",
   "type": "graph",
   "description": "This can show a correlation with the replication lag value",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_ping_ms{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"} * on (name) group_right(state) (max_over_time(mongodb_mongod_replset_my_name{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}[$interval]) or max_over_time(mongodb_mongod_replset_my_name{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Oplog Getmore Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mongodb_mongod_metrics_repl_network_getmores_total_milliseconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}[$interval]) or irate(mongodb_mongod_metrics_repl_network_getmores_total_milliseconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Oplog Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mongodb_mongod_metrics_repl_preload_docs_num_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_docs_num_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Document Preload"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mongodb_mongod_metrics_repl_preload_indexes_num_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_indexes_num_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Index Preload"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mongodb_mongod_metrics_repl_apply_ops_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}[$interval]) or irate(mongodb_mongod_metrics_repl_apply_ops_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Batch Apply"
    }
   ]
  },
  {
   "title": "Oplog Processing Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mongodb_mongod_metrics_repl_preload_docs_total_milliseconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_docs_total_milliseconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Document Preload"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mongodb_mongod_metrics_repl_preload_indexes_total_milliseconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_indexes_total_milliseconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Index Preload"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mongodb_mongod_metrics_repl_apply_batches_total_milliseconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}[$interval]) or irate(mongodb_mongod_metrics_repl_apply_batches_total_milliseconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Batch Apply"
    }
   ]
  },
  {
   "title": "Oplog Buffered Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (mongodb_mongod_metrics_repl_buffer_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Current"
    }
   ]
  },
  {
   "title": "Oplog Buffer Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (mongodb_mongod_metrics_repl_buffer_size_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Used"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (mongodb_mongod_metrics_repl_buffer_max_size_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",set=~\"$replset\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Max"
    }
   ]
  }
 ]
}