{
 "title": "MySQL Performance Schema",
 "description": "MySQL Performance Schema metrics overview.",
 "tags": [
  "database",
  "mysql",
  "sgbd"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(mysql_global_variables_performance_schema,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(mysql_global_variables_performance_schema{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(mysql_global_variables_performance_schema{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "host",
    "label": "Pod Name",
    "query": "label_values(mysql_global_variables_performance_schema{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Performance Schema File IO (Events)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,event_name,mode) (rate(mysql_perf_schema_file_events_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) > 0)) or topk(10,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,event_name,mode) (irate(mysql_perf_schema_file_events_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) > 0))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{event_name}} {{mode}}"
    }
   ]
  },
  {
   "title": "Performance Schema File IO (Load)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,event_name,mode) (rate(mysql_perf_schema_file_events_seconds_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) > 0)) or topk(10,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,event_name,mode) (irate(mysql_perf_schema_file_events_seconds_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) > 0))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{event_name}} {{mode}}"
    }
   ]
  },
  {
   "title": "Performance Schema File IO (Bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,event_name,mode) (rate(mysql_perf_schema_file_events_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) > 0)) or topk(10,(sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,event_name,mode) (irate(mysql_perf_schema_file_events_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) > 0)))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{event_name}} {{mode}}"
    }
   ]
  },
  {
   "title": "Performance Schema Waits (Events)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,event_name) (rate(mysql_perf_schema_events_waits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) > 0)) or topk(5,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,event_name) (irate(mysql_perf_schema_events_waits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) > 0))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{event_name}} "
    }
   ]
  },
  {
   "title": "Performance Schema Waits (Load)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,event_name) (rate(mysql_perf_schema_events_waits_seconds_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$host\",event_name!='idle',event_name!='wait/io/table/sql/handler'}[$interval]) > 0)) or topk(5,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,event_name) (irate(mysql_perf_schema_events_waits_seconds_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$host\",event_name!='idle',event_name!='wait/io/table/sql/handler'}[5m]) > 0))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{event_name}} "
    }
   ]
  },
  {
   "title": "Index Access Operations (Load)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,operation,index,schema,name) (rate(mysql_perf_schema_index_io_waits_seconds_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) > 0)) or topk(5,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,operation,index,schema,name) (irate(mysql_perf_schema_index_io_waits_seconds_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) > 0))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{operation}} {{index}} {{schema}}.{{name}}"
    }
   ]
  },
  {
   "title": "Table Access Operations (Load)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,operation,index,schema,name) (rate(mysql_perf_schema_table_io_waits_seconds_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) > 0)) or topk(5,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,operation,index,schema,name) (irate(mysql_perf_schema_table_io_waits_seconds_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) > 0))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{operation}} {{schema}}.{{name}}"
    }
   ]
  },
  {
   "title": "Performance Schema SQL & External Locks (Events)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,operation,schema) (rate(mysql_perf_schema_sql_lock_waits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]))) or topk(10,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,operation,schema) (irate(mysql_perf_schema_sql_lock_waits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m])))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} SQL Lock Waits {{schema}}.{{operation}}"
    },
    {
     "expr": "topk(10,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,operation,schema) (rate(mysql_perf_schema_external_lock_waits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) > 0)) or topk(10,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,operation,schema) (irate(mysql_perf_schema_external_lock_waits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) > 0))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} External Lock Waits {{schema}}.{{operation}}"
    }
   ]
  },
  {
   "title": "Performance Schema SQL and External Locks (Seconds)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,operation,name,schema) (rate(mysql_perf_schema_external_lock_waits_seconds_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$host\"}[$interval]) > 0)) or topk(10,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,operation,name,schema) (irate(mysql_perf_schema_external_lock_waits_seconds_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$host\"}[5m]) > 0))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} External Locks Waits {{schema}}.{{name}}.{{operation}}"
    },
    {
     "expr": "topk(10,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,operation,name,schema) (rate(mysql_perf_schema_sql_lock_waits_seconds_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$host\"}[$interval]) > 0)) or topk(10,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,operation,name,schema) (irate(mysql_perf_schema_sql_lock_waits_seconds_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$host\"}[5m]) > 0))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} SQL Locks Waits {{schema}}.{{name}}.{{operation}}"
    }
   ]
  }
 ]
}