{
 "title": "MySQL InnoDB Compression",
 "description": "MySQL InnoDB Compression metrics overview.",
 "tags": [
  "database",
  "mysql",
  "sgbd"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(mysql_global_variables_innodb_compression_failure_threshold_pct{},kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(mysql_global_variables_innodb_compression_failure_threshold_pct{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(mysql_global_variables_innodb_compression_failure_threshold_pct{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "host",
    "label": "Pod Name",
    "query": "label_values(mysql_global_variables_innodb_compression_failure_threshold_pct{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"},kubernetes_pod_name)"
   },
   {
    "name": "buffer",
    "label": "Buffer Pool",
    "query": "label_values(mysql_info_schema_innodb_cmpmem_pages_used_total{kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$host\"},buffer_pool)"
   }
  ]
 },
 "panels": [
  {
   "title": "Compression level and failure rate threshold",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "InnoDB Compression level (max)",
   "type": "singlestat",
   "description": "The level of zlib compression to use for InnoDB compressed tables and indexes.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(mysql_global_variables_innodb_compression_level{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"})"
    }
   ]
  },
  {
   "title": "InnoDB Compression Failure Threshold (max)",
   "type": "singlestat",
   "description": "The compression failure rate threshold for a table",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(mysql_global_variables_innodb_compression_failure_threshold_pct{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Compression Failure Rate Threshold (max)",
   "type": "singlestat",
   "description": "The maximum percentage that can be reserved as free space within each compressed page, allowing room to reorganize the data and modification log within the page when a compressed table or index is updated and the data might be recompressed.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(mysql_global_variables_innodb_compression_pad_pct_max{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Write Pages to The Redo Log (max)",
   "type": "singlestat",
   "description": "Specifies whether images of re-compressed pages are written to the redo log. Re-compression may occur when changes are made to compressed data.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(mysql_global_variables_innodb_log_compressed_pages{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Statistic of compression operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Compress Attempts",
   "type": "graph",
   "description": "Number of compression operations attempted. Pages are compressed whenever an empty page is created or the space for the uncompressed modification log runs out.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,page_size) (rate(mysql_info_schema_innodb_cmp_compress_ops_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_cmp_compress_ops_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{page_size}}"
    }
   ]
  },
  {
   "title": "Uncompressed Attempts",
   "type": "graph",
   "description": "Number of uncompression operations performed. Compressed InnoDB pages are uncompressed whenever compression fails, or the first time a compressed page is accessed in the buffer pool and the uncompressed page does not exist.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,page_size) (rate(mysql_info_schema_innodb_cmp_uncompress_ops_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_cmp_uncompress_ops_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{page_size}}"
    }
   ]
  },
  {
   "title": "Compression Success Ratio",
   "type": "graph",
   "description": "Shows the ratio between Success InnoDB Compress vs the total InnoDB Compress operations. A high ration indicates that InnoDB compression is being effective and helping to save disk space.\n\nSee also:",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,page_size) (rate(mysql_info_schema_innodb_cmp_compress_ops_ok_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) / rate(mysql_info_schema_innodb_cmp_compress_ops_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or rate(mysql_info_schema_innodb_cmp_compress_ops_ok_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) / rate(mysql_info_schema_innodb_cmp_compress_ops_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{page_size}}"
    }
   ]
  },
  { "title": "Buffer Pool Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Total Used Pages",
   "type": "graph",
   "description": "Shows the total amount of used compressed pages into the InnoDB Buffer Pool split by page size.\n\nSee also:",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,page_size) (mysql_info_schema_innodb_cmpmem_pages_used_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{page_size}}"
    }
   ]
  },
  {
   "title": "Total Free Pages",
   "type": "graph",
   "description": "Shows the total amount of free compressed pages into the InnoDB Buffer Pool split by page size.\n\nSee also:",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,page_size) (mysql_info_schema_innodb_cmpmem_pages_free_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{page_size}}"
    }
   ]
  },
  { "title": "Buffer Pool  $buffer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }, "repeat": "buffer" },
  {
   "title": "Used Pages (Buffer Pull $buffer)",
   "type": "graph",
   "description": "Shows the amount of used compressed pages into this InnoDB Buffer Pool instance split by page size.\n\nSee also:",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,page_size) (mysql_info_schema_innodb_cmpmem_pages_used_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",buffer_pool=~\"$buffer\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{page_size}}"
    }
   ]
  },
  {
   "title": "Pages Free (Buffer Pull $buffer)",
   "type": "graph",
   "description": "Shows the amount of free compressed pages into this InnoDB Buffer Pool instance split by page size.\n\nSee also:",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,page_size) (mysql_info_schema_innodb_cmpmem_pages_free_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",buffer_pool=\"$buffer\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{page_size}}"
    }
   ]
  }
 ]
}