{
 "title": "MySQL InnoDB Metrics Advanced",
 "description": "MySQL InnoDB metrics overview.",
 "tags": [
  "database",
  "mysql",
  "sgbd"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_insert_total,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_insert_total{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_insert_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "host",
    "label": "Pod Name",
    "query": "label_values(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_insert_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Change Buffer Performance",
   "type": "graph",
   "description": "The Change Buffer Performance graph shows the activity on the InnoDB change buffer.  The InnoDB change buffer records updates to non-unique secondary keys when the destination page is not in the buffer pool.  The updates are applied when the page is loaded in the buffer pool, prior to its use by a query.  Merge ratio is the number of insert buffer changes done per page, the higher the ratio the better is the efficiency of the change buffer.\n\nNote: If you do not see any metric, try running: ``SET GLOBAL innodb_monitor_enable=all;`` in the MySQL client.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_insert_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_insert_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Ibuf Insert"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Ibuf Delete"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_mark_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_mark_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Ibuf Delete Mark"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Ibuf Merges"
    }
   ]
  },
  {
   "title": "InnoDB Log Buffer Performance",
   "type": "graph",
   "description": "The InnoDB Log Buffer Performance graph shows the efficiency of the InnoDB log buffer.  The InnoDB log buffer size is defined by the innodb_log_buffer_size parameter and illustrated on the graph by the Size metric.  Used is the amount of the buffer space that is used.  If Used is too high and gets close to Size, additional log writes will be required.\n\nNote: If you do not see any metric, try running: ``SET GLOBAL innodb_monitor_enable=all;`` in the MySQL client.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (mysql_global_variables_innodb_log_buffer_size{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Size"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (mysql_info_schema_innodb_metrics_recovery_log_lsn_current{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"} - mysql_info_schema_innodb_metrics_recovery_log_lsn_last_flush{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}Used"
    }
   ]
  },
  {
   "title": "InnoDB Page Splits",
   "type": "graph",
   "description": "The InnoDB Page Splits graph shows the InnoDB page maintenance activity related to splitting and merging pages.  When an InnoDB page, other than the top most leaf page, has too much data to accept a row update or a row insert, it has to be split in two.  Similarly, if an InnoDB page, after a row update or delete operation, ends up being less than half full, an attempt is made to merge the page with a neighbor page. If the resulting page size is larger than the InnoDB page size, the operation fails.  If your workload causes a large number of page splits, try lowering the innodb_fill_factor variable (5.7+).\n\nNote: If you do not see any metric, try running: ``SET GLOBAL innodb_monitor_enable=all;`` in the MySQL client.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Pages" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_index_index_page_merge_attempts_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_index_index_page_merge_attempts_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Index Page Merge Attempts"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_index_index_page_merge_successful_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_index_index_page_merge_successful_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Index Page Merge Successful"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_index_index_page_splits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_index_index_page_splits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Index Page Splits"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) ((rate(mysql_info_schema_innodb_metrics_index_index_page_merge_successful_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_index_index_page_merge_successful_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m])) / (rate(mysql_info_schema_innodb_metrics_index_index_page_merge_attempts_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_index_index_page_merge_attempts_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m])) * 100)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Page Merge Successes / Page Merge Attempts"
    }
   ]
  },
  {
   "title": "InnoDB Page Reorgs",
   "type": "graph",
   "description": "The InnoDB Page Reorgs graph shows information about the page reorganization operations.  When a page receives an  update or an insert that affect the offset of other rows in the page, a reorganization is needed.  If the reorganization process finds out there is not enough room in the page, the page will be split. Page reorganization can only fail for compressed pages.\n\nNote: If you do not see any metric, try running: ``SET GLOBAL innodb_monitor_enable=all;`` in the MySQL client.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_index_index_page_reorg_attempts_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_index_index_page_reorg_attempts_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Index Page Reorg Attempts"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_index_index_page_reorg_successful_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_index_index_page_reorg_successful_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Index Page Reorg Successful"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) ((rate(mysql_info_schema_innodb_metrics_index_index_page_reorg_successful_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_index_index_page_reorg_successful_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m])) / (rate(mysql_info_schema_innodb_metrics_index_index_page_reorg_attempts_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_index_index_page_reorg_attempts_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m])) * 100)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Reorg Successes / Reorg Attempts"
    }
   ]
  },
  {
   "title": "InnoDB Purge Performance",
   "type": "graph",
   "description": "The InnoDB Purge Performance graph shows metrics about the page purging process.  The purge process removed the undo entries from the history list and cleanup the pages of the old versions of modified rows and effectively remove deleted rows.\n\nNote: If you do not see any metric, try running: ``SET GLOBAL innodb_monitor_enable=all;`` in the MySQL client.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_purge_purge_upd_exist_or_extern_records_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_purge_purge_upd_exist_or_extern_records_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Updates Purged"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_purge_purge_del_mark_records_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_purge_purge_del_mark_records_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Deletes Purged"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_purge_purge_undo_log_pages_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_purge_purge_undo_log_pages_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Pages Purged"
    }
   ]
  },
  {
   "title": "InnoDB Locking",
   "type": "graph",
   "description": "The InnoDB Locking graph shows the row level lock activity inside InnoDB. \n\nNote: If you do not see any metric, try running: ``SET GLOBAL innodb_monitor_enable=all;`` in the MySQL client.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_lock_lock_rec_lock_created_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_lock_lock_rec_lock_created_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Locks Created"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_lock_lock_rec_lock_removed_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_lock_lock_rec_lock_removed_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Locks Removed"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_lock_lock_rec_lock_requests_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_lock_lock_rec_lock_requests_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Locks Requested"
    }
   ]
  },
  {
   "title": "InnoDB Main Thread Utilization",
   "type": "graph",
   "description": "The InnoDB Main Thread Utilization graph shows the portion of time the InnoDB main thread spent at various task.\n\nNote: If you do not see any metric, try running: ``SET GLOBAL innodb_monitor_enable=all;`` in the MySQL client.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_server_innodb_log_flush_usec_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) / 1000000 or irate(mysql_info_schema_innodb_metrics_server_innodb_log_flush_usec_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) / 1000000)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Log Flushing"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_server_innodb_ibuf_merge_usec_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) / 1000000 or irate(mysql_info_schema_innodb_metrics_server_innodb_ibuf_merge_usec_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) / 1000000)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Insert Buffer Merging"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_server_innodb_checkpoint_usec_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) / 1000000 or irate(mysql_info_schema_innodb_metrics_server_innodb_checkpoint_usec_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) / 1000000)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Checkpointing"
    }
   ]
  },
  {
   "title": "InnoDB Transactions Information",
   "type": "graph",
   "description": "The InnoDB Transactions Information graph shows details about the recent transactions.  Transaction IDs Assigned represents the total number of transactions initiated by InnoDB.  RW Transaction Commits are the number of transactions not read-only. Insert-Update Transactions Commits are transactions on the Undo entries.  Non Locking RO Transaction Commits are transactions commit from select statement in auto-commit mode or transactions explicitly started with \"start transaction read only\".\n\nNote: If you do not see any metric, try running: ``SET GLOBAL innodb_monitor_enable=all;`` in the MySQL client.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_transaction_trx_rw_commits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_transaction_trx_rw_commits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} RW Transacton Commits "
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_transaction_trx_rollbacks_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_transaction_trx_rollbacks_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Transaction Rollbacks"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_transaction_trx_ro_commits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_transaction_trx_ro_commits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} RO Transaction Commits"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_transaction_trx_nl_ro_commits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_transaction_trx_nl_ro_commits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Non Locking RO Transaction Commits"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_transaction_trx_commits_insert_update_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_transaction_trx_commits_insert_update_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Insert-Update Transaction Commits"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_max_trx_id{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_max_trx_id{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Transaction IDs Assigned"
    }
   ]
  },
  {
   "title": "InnoDB Undo Space Usage",
   "type": "graph",
   "description": "The InnoDB Undo Space Usage graph shows the amount of space used by the Undo segment.  If the amount of space grows too much, look for long running transactions holding read views opened in the InnoDB status.\n\nNote: If you do not see any metric, try running: ``SET GLOBAL innodb_monitor_enable=all;`` in the MySQL client.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (mysql_info_schema_innodb_metrics_transaction_trx_rseg_current_size{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"} * mysql_global_status_innodb_page_size{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Innodb Undo Space Used "
    }
   ]
  },
  {
   "title": "InnoDB Activity",
   "type": "graph",
   "description": "The InnoDB Acitivity graph shows a measure of the activity of the InnoDB threads. \n\nNote: If you do not see any metric, try running: ``SET GLOBAL innodb_monitor_enable=all;`` in the MySQL client.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_server_innodb_activity_count_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_server_innodb_activity_count_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} InnoDB Activity"
    }
   ]
  },
  {
   "title": "InnoDB Contention - OS Waits",
   "type": "graph",
   "description": "The InnoDB Contention - OS Waits graph shows the number of time an OS wait operation was required while waiting to get the lock.  This happens once the spin rounds are exhausted.\n\nNote: If you do not see any metric, try running: ``SET GLOBAL innodb_monitor_enable=all;`` in the MySQL client.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_s_os_waits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_s_os_waits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} RW Locks S OS Waits"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_sx_os_waits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_sx_os_waits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} RW Locks SX OS Waits"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_x_os_waits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_x_os_waits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} RW Locks X OS Waits"
    }
   ]
  },
  {
   "title": "InnoDB Contention - Spin Rounds",
   "type": "graph",
   "description": "The InnoDB Contention - Spin Rounds  graph shows the number of spin rounds executed in order to get a lock.  A spin round is a fast retry to get the lock in a loop.\n\nNote: If you do not see any metric, try running: ``SET GLOBAL innodb_monitor_enable=all;`` in the MySQL client.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_s_spin_rounds_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_s_spin_rounds_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} RW Locks S Spin Rounds"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_sx_spin_rounds_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_sx_spin_rounds_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} RW Locks SX Spin Rounds"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_x_spin_rounds_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_server_innodb_rwlock_x_spin_rounds_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} RW Locks X Spin Rounds"
    }
   ]
  },
  {
   "title": "InnoDB Group Commit Batch Size",
   "type": "graph",
   "description": "The InnoDB Group Commit Batch Size graph shows how many bytes were written to the InnoDB log files per attempt to write.  If many threads are committing at the same time, one of them will write the log entries of all the waiting threads and flush the file.  Such process reduces the number of disk operations needed and enlarge the batch size.\n\nNote: If you do not see any metric, try running: ``SET GLOBAL innodb_monitor_enable=all;`` in the MySQL client.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_transaction_trx_rw_commits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval])/rate(mysql_global_status_innodb_log_writes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_transaction_trx_rw_commits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m])/irate(mysql_global_status_innodb_log_writes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Group Commit Batch Size"
    }
   ]
  },
  {
   "title": "InnoDB Purge Throttling",
   "type": "graph",
   "description": "The InnoDB Purge Throttling graph shows the evolution of the purge lag and the max purge lag currently set.  Under heavy write load, the purge operation may start to lag behind and when the max purge lag is reached, a delay, proportional to the value defined by innodb_max_purge_lag_delay (in microseconds) is added to all update, insert and delete statements.  This helps prevents flushing stalls.\n\nNote: If you do not see any metric, try running: ``SET GLOBAL innodb_monitor_enable=all;`` in the MySQL client.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (mysql_info_schema_innodb_metrics_purge_purge_dml_delay_usec{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Current Purge Delay"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (mysql_global_variables_innodb_max_purge_lag_delay{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Max Purge Delay"
    }
   ]
  },
  {
   "title": "InnoDB AHI Usage",
   "type": "graph",
   "description": "The InnoDB AHI Usage graph shows the search operations on the InnoDB adaptive hash index and its efficiency.  The adaptive hash index is a search hash designed to speed access to InnoDB pages in memory.  If the Hit Ratio is small, the working data set is larger than the buffer pool, the AHI should likely be disabled.\n\nNote: If you do not see any metric, try running: ``SET GLOBAL innodb_monitor_enable=all;`` in the MySQL client.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_btree_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval])+rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_btree_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m])+irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} AHI - Total Searches"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} AHI - Misses"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (1 - (rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval])) / (rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval])+rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_btree_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval])) or 1 - (irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m])) / (irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) + irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_btree_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m])))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} AHI - Hit Ratio"
    }
   ]
  },
  {
   "title": "InnoDB AHI Maintenance",
   "type": "graph",
   "description": "The InnoDB AHI Maintenance graph shows the maintenance operation of the InnoDB adaptive hash index.  The adaptive hash index is a search hash to speed access to InnoDB pages in memory. A constant high number of rows/pages added and removed can be an indication of an ineffective AHI.\n\nNote: If you do not see any metric, try running: ``SET GLOBAL innodb_monitor_enable=all;`` in the MySQL client.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_pages_added_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_pages_added_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} AHI - Pages Added"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_pages_removed_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_pages_removed_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} AHI - Pages Removed"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_added_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate( mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_added_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} AHI - Rows Added"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_removed_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_removed_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} AHI - Rows Removed"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_updated_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_updated_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} AHI - Rows Updated"
    }
   ]
  },
  {
   "title": "InnoDB Online DDL",
   "type": "graph",
   "description": "The InnoDB Online DDL graph shows the state of the online DDL (alter table) operations in InnoDB.  The progress metric is estimate of the percentage of the rows processed by the online DDL.\n\nNote: Currently available only on a MariaDB server.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_innodb_onlineddl_pct_progress{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"} / 100",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} % Progress"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_onlineddl_rowlog_pct_used{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_onlineddl_rowlog_pct_used{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Row Log % Used"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_onlineddl_rowlog_rows{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_onlineddl_rowlog_rows{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Row Log Rows"
    }
   ]
  },
  {
   "title": "InnoDB Defragmentation",
   "type": "graph",
   "description": "The InnoDB Defragmentation graph shows the status information related to the InnoDB online defragmentation feature of MariaDB for the optimize table command.  To enable this feature, the variable innodb-defragment must be set to 1 in the configuration file.\n\nNote: Currently available only on a MariaDB server.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_defragment_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_defragment_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Count"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_defragment_compression_failures{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_defragment_compression_failures{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Re-Compression Failures"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_defragment_failures{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_defragment_failures{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Failures"
    }
   ]
  }
 ]
}