{
 "title": "NextCloud",
 "description": "NextCloud metrics overview.",
 "tags": [
  "applications",
  "php",
  "nextcloud"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "30m,1h,3h,6h,12h,1d,7d,14d,30d" },
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(nextcloud_users_total,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(nextcloud_users_total{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(nextcloud_users_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "podname",
    "label": "Pod Name",
    "query": "label_values(nextcloud_users_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "NextCloud Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(nextcloud_up{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}) / count(nextcloud_up{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Auth Errors by $interval",
   "type": "graph",
   "gridPos": { "h": 3, "w": 10, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(nextcloud_auth_errors_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[$interval]))",
     "legendFormat": "Auth Errors"
    }
   ]
  },
  {
   "title": "Files Upload by $interval",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (kubernetes_namespace,kubernetes_cluster,kubernetes_service_name) (increase(nextcloud_files_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[$interval]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "User Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (nextcloud_users_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"})",
     "legendFormat": "Users Total"
    },
    {
     "expr": "sum (nextcloud_active_users_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"})",
     "legendFormat": "Users Active"
    }
   ]
  },
  {
   "title": "Total Files Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (nextcloud_files_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"})",
     "legendFormat": "Files Total"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name) (nextcloud_database_size_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "Shares",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nextcloud_shares_federated_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"})",
     "legendFormat": "Federated Total"
    },
    {
     "expr": "sum(nextcloud_shares_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"})",
     "legendFormat": "Total Shares"
    }
   ]
  },
  {
   "title": "Scrape Errors in $interval",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase (nextcloud_scrape_errors_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[$interval]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}