{
 "title": "NodeJS Applications",
 "description": "Node.JS Applications overview.",
 "tags": [
  "application",
  "nodejs"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(nodejs_version_info,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(nodejs_version_info{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(nodejs_version_info{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "podname",
    "label": "Pod Name",
    "query": "label_values(nodejs_version_info{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\"}[2m]) * 100",
     "legendFormat": "User CPU - {{kubernetes_namespace}}/{{kubernetes_pod_name}} ({{kubernetes_cluster}})"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\"}[2m]) * 100",
     "legendFormat": "Sys CPU - {{kubernetes_namespace}}/{{kubernetes_pod_name}} ({{kubernetes_cluster}})"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} ({{kubernetes_cluster}})"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "bottomk(1,sum(nodejs_version_info{kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\"}) by (version))",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "Process Memory - {{kubernetes_namespace}}/{{kubernetes_pod_name}} ({{kubernetes_cluster}})"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "Heap Total - {{kubernetes_namespace}}/{{kubernetes_pod_name}} ({{kubernetes_cluster}})"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "Heap Used - {{kubernetes_namespace}}/{{kubernetes_pod_name}} ({{kubernetes_cluster}})"
    },
    {
     "expr": "nodejs_external_memory_bytes{kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "External Memory - {{kubernetes_namespace}}/{{kubernetes_pod_name}} ({{kubernetes_cluster}})"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "Active Handler - {{kubernetes_namespace}}/{{kubernetes_pod_name}} ({{kubernetes_cluster}})"
    },
    {
     "expr": "nodejs_active_requests_total{kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "Active Request - {{kubernetes_namespace}}/{{kubernetes_pod_name}} ({{kubernetes_cluster}})"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "Heap Total - {{kubernetes_namespace}}/{{kubernetes_pod_name}} - {{space}} ({{kubernetes_cluster}})"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "Heap Used - {{kubernetes_namespace}}/{{kubernetes_pod_name}} - {{space}} ({{kubernetes_cluster}})"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "Heap Available - {{kubernetes_namespace}}/{{kubernetes_pod_name}} - {{space}} ({{kubernetes_cluster}})"
    }
   ]
  }
 ]
}