{
 "title": "NodeJS Metrics",
 "description": "Node.JS Runtime metrics overview.",
 "tags": [
  "application",
  "nodejs"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "10s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(nodejs_version_info,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(nodejs_version_info{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(nodejs_version_info{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "podname",
    "label": "Pod Name",
    "query": "label_values(nodejs_version_info{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Service Nodejs Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "repeat": "service",
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "bottomk(1,sum(nodejs_version_info{kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\"}) by (version))",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_requests{kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "Active {{type}} {{kubernetes_namespace}}/{{kubernetes_pod_name}} ({{kubernetes_cluster}})"
    },
    {
     "expr": "nodejs_active_requests_total{kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "Total {{kubernetes_namespace}}/{{kubernetes_pod_name}} ({{kubernetes_cluster}})"
    }
   ]
  },
  {
   "title": "Active Handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles{kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "Active {{type}} {{kubernetes_namespace}}/{{kubernetes_pod_name}} ({{kubernetes_cluster}})"
    },
    {
     "expr": "nodejs_active_handles_total{kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "Total {{kubernetes_namespace}}/{{kubernetes_pod_name}} ({{kubernetes_cluster}})"
    }
   ]
  },
  {
   "title": "Service Process Heap (max)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "repeat": "service",
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(process_heap_bytes{kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Last Process Restart",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Service Max file descriptors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "repeat": "service",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(process_max_fds{kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Service Metrics scrape duration sum",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "repeat": "service",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(scrape_duration_seconds{kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total{kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_cluster=~\"$cluster\"}[$interval])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} User ({{kubernetes_cluster}})"
    },
    {
     "expr": "rate(process_cpu_system_seconds_total{kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_cluster=~\"$cluster\"}[$interval])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} System ({{kubernetes_cluster}})"
    },
    {
     "expr": "rate(process_cpu_seconds_total{kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_cluster=~\"$cluster\"}[$interval])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Total ({{kubernetes_cluster}})"
    }
   ]
  },
  {
   "title": "Event loop lag",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Event Loop Lag ({{kubernetes_cluster}})"
    }
   ]
  },
  {
   "title": "Maximum Opened file descriptors",
   "type": "singlestat",
   "description": "Given collected process opened fds , returns the maximum value",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "repeat": "service",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(process_open_fds{kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_cluster=~\"$cluster\"})"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "External Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_external_memory_bytes{kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} External Memory ({{kubernetes_cluster}})"
    }
   ]
  },
  {
   "title": "Heap size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Total ({{kubernetes_cluster}})"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Used ({{kubernetes_cluster}})"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Resident ({{kubernetes_cluster}})"
    },
    {
     "expr": "process_virtual_memory_bytes{kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Virtual ({{kubernetes_cluster}})"
    }
   ]
  },
  { "title": "Heap Space Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{space}} ({{kubernetes_cluster}})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{space}} ({{kubernetes_cluster}})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\",kubernetes_cluster=~\"$cluster\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{space}} ({{kubernetes_cluster}})"
    }
   ]
  }
 ]
}