{
 "title": "OpenLDAP",
 "description": "OpenLDAP metrics overview.",
 "tags": [
  "database",
  "x509",
  "openldap"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(openldap_monitored_op,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(openldap_monitored_op{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(openldap_monitored_op{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "instance",
    "label": "Pod Name",
    "query": "label_values(openldap_monitored_op{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Operations",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,status) (label_replace(rate(openldap_monitored_op{dn=~\"cn=[a-zA-Z]+,cn=Operations,cn=Monitor\"}[5m]), \"status\", \"$1\", \"dn\", \"cn=([a-zA-Z]+),.*\"))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{status}}",
     "target": "aliasByNode(perSecond(servers.seaborgium.openldap.ops.*), 4)"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (ldap_monitor_counter_object{dn=~\"cn=Current,cn=Connections,cn=Monitor\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} current",
     "target": "aliasByMetric(servers.seaborgium.openldap.conns.current)"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(ldap_monitor_counter_object{dn=\"cn=Bytes,cn=Statistics,cn=Monitor\"}[5m]) / 1024)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} kbytes",
     "target": "alias(scale(perSecond(servers.seaborgium.openldap.stats.bytes), 0.001), 'kilobytes')"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(ldap_monitor_counter_object{dn=\"cn=PDU,cn=Statistics,cn=Monitor\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} PDU",
     "target": "aliasByNode(perSecond(servers.seaborgium.openldap.stats.pdu), 4)"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(ldap_monitor_counter_object{dn=\"cn=Entries,cn=Statistics,cn=Monitor\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} entries",
     "target": "aliasByNode(perSecond(servers.seaborgium.openldap.stats.entries), 4)"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,status) (label_replace(ldap_monitored_object{dn=~\"cn=[a-zA-Z]+,cn=Threads,cn=Monitor\"}, \"status\", \"$1\", \"dn\", \"cn=([a-zA-Z]+),.*\"))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{status}}",
     "target": "aliasByMetric(servers.seaborgium.openldap.threads.*)"
    }
   ]
  },
  {
   "title": "OpenLDAP waiters",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,status) (label_replace(ldap_monitor_counter_object{dn=~\"cn=[a-zA-Z]+,cn=Waiters,cn=Monitor\"}, \"status\", \"$1\", \"dn\", \"cn=([a-zA-Z]+),.*\"))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{status}}",
     "target": "aliasByMetric(servers.seaborgium.openldap.waiter.*)"
    }
   ]
  }
 ]
}