{
 "title": "Postfix",
 "description": "Postfix metrics overview.",
 "tags": [
  "mails",
  "postfix",
  "smtp"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "1m,5m,10m,30m,1h,6h,12h" },
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(postfix_up,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(postfix_up{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(postfix_up{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "pod",
    "label": "Kubernetes Pod",
    "query": "label_values(postfix_up{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "cleanup(8)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Message processing per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_cleanup_messages_processed_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Rejection per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_cleanup_messages_rejected_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }}"
    }
   ]
  },
  { "title": "lmtp(8)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Message processing per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_lmtp_delivery_delay_seconds_count{stage=\"queue_manager\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Average delivery duration by stage per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum by (stage,kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_lmtp_delivery_delay_seconds_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))) / (sum by (stage,kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_lmtp_delivery_delay_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval])))",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }} {{ stage }}"
    }
   ]
  },
  { "title": "pipe(8)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Message processing per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (relay,stage,kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_pipe_delivery_delay_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }} {{relay}} {{stage}}"
    }
   ]
  },
  {
   "title": "Average delivery duration by stage per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (stage,kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_pipe_delivery_delay_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }} {{ stage }}"
    }
   ]
  },
  { "title": "qmgr(8)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Message insertion per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_qmgr_messages_inserted_size_bytes_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Messages insertions in bytes per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_qmgr_messages_inserted_size_bytes_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Messages removal per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_qmgr_messages_removed_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }}"
    }
   ]
  },
  { "title": "showq(8)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Number of enqueued messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (queue,kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (postfix_showq_messages_size_bytes_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }} {{ queue }}"
    }
   ]
  },
  {
   "title": "Size of enqueued messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (queue,kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (postfix_showq_messages_size_bytes_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }} {{ queue }}"
    }
   ]
  },
  {
   "title": "Average age of enqueued messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum by (queue,kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (postfix_showq_message_age_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})) / (count by (queue,kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (postfix_showq_message_age_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }} {{ queue }}"
    }
   ]
  },
  { "title": "smtp(8)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Message processing per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (stage,kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_smtp_delivery_delay_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }} {{ stage }}"
    }
   ]
  },
  {
   "title": "Average delivery duration by stage per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum by (stage,kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_smtp_delivery_delay_seconds_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))) / (sum by (stage,kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_smtp_delivery_delay_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))) ",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }} {{ stage }}"
    }
   ]
  },
  {
   "title": "TLS conection ratio per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_smtp_tls_connections_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))) / (sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_smtp_delivery_delay_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval])))",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "TLS protocol/cipher usage per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (protocol,cipher,trust,kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_smtp_tls_connections_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }} {{ protocol }}:{{ cipher }}, {{ trust }}"
    }
   ]
  },
  { "title": "smtpd(8)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Connects per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_smtpd_connects_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Disconnects per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_smtpd_disconnects_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Connections lost per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (after_stage,kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_smtpd_connections_lost_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }} {{ after_stage }}"
    }
   ]
  },
  {
   "title": "SASL authentication failures per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_smtpd_sasl_authentication_failures_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Forward-confirmed reverse DNS erros per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_smtpd_forward_confirmed_reverse_dns_errors_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Message processing per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_smtpd_messages_processed_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Rejections per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (code,kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_smtpd_messages_rejected_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }} {{ code }}"
    }
   ]
  },
  {
   "title": "TLS conections per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_smtpd_tls_connections_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))) / (sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_smtpd_connects_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval])))",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "TLS protocol/cipher usage per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (protocol,cipher,trust,kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(postfix_smtpd_tls_connections_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "{{ kubernetes_namespace }}/{{ kubernetes_pod_name }} {{ protocol }}:{{ cipher }}, {{ trust }}"
    }
   ]
  }
 ]
}