{
 "title": "Postgres",
 "description": "Postgres metrics overview.",
 "tags": [
  "database",
  "postgres",
  "sgbd"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "kube",
    "label": "Kubernetes Cluster",
    "query": "label_values(pg_exporter_scrapes_total{},kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(pg_exporter_scrapes_total{kubernetes_cluster=~\"$kube\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(pg_exporter_scrapes_total{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "host",
    "label": "Kubernetes Host",
    "query": "label_values(pg_exporter_scrapes_total{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"},kubernetes_node_name)"
   },
   {
    "name": "instance",
    "label": "Pod Name",
    "query": "label_values(pg_exporter_scrapes_total{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_node_name=~\"$host\"},kubernetes_pod_name)"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "label_values(node_disk_reads_completed_total{kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\",device!~\"dm-.+\"},device)"
   },
   {
    "name": "datname",
    "label": "Database",
    "query": "label_values(pg_stat_database_checksum_last_failure{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_node_name=~\"$host\",kubernetes_pod_name=~\"$instance\"},datname)"
   },
   {
    "name": "mode",
    "label": "Lock table",
    "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"},mode)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current IOwait",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\",mode=\"iowait\"}[$interval])) by (mode)* 100 / scalar(count(node_cpu_seconds_total{mode=\"user\",kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\"})) or sum(irate(node_cpu_seconds_total{kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\",mode=\"iowait\"}[5m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\",kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\"}))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Current CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\",mode=\"user\"}[$interval])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\",kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\"})) or sum(irate(node_cpu_seconds_total{kubernetes_host_name=~\"$host\",mode=\"user\"}[5m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\",kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\"}))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "RAM used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum((node_memory_MemTotal_bytes{kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\"} - (node_memory_MemFree_bytes{kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\"} + node_memory_Buffers_bytes{kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\"} + node_memory_Cached_bytes{kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\"}))) / sum(node_memory_MemTotal_bytes{kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\"})) * 100",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "RAM cached",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum((node_memory_Cached_bytes{kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\"}) * 100) / sum(node_memory_MemTotal_bytes{kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\"})",
     "legendFormat": "Memory Cached"
    }
   ]
  },
  {
   "title": "Current fetch data",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\",kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_inserted{datname=~\"$datname\",kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\",kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Fetch data (SELECT)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{datname=~\"$datname\",kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$instance\"} != 0",
     "legendFormat": "{{kubernetes_pod_name}}/{{datname}}"
    }
   ]
  },
  {
   "title": "Insert data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=~\"$datname\",kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$instance\"} != 0",
     "legendFormat": "{{kubernetes_pod_name}}/{{datname}}"
    }
   ]
  },
  {
   "title": "Update data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{datname=~\"$datname\",kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$instance\"} != 0",
     "legendFormat": "{{kubernetes_pod_name}}/{{datname}}"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\",kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$instance\",state=\"active\"} != 0",
     "legendFormat": "{{kubernetes_pod_name}}/{{datname}}"
    }
   ]
  },
  {
   "title": "Idle sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\",kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$instance\",state=~\"idle|idle in transaction|idle in transaction (aborted)\"} != 0",
     "legendFormat": "{{kubernetes_pod_name}}/{{datname}} ({{state}})"
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{device=~\"$device\",kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\"}[$interval]) * 100 or irate(node_disk_io_time_seconds_total{device=~\"$device\",kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\"}[$interval]) * 100",
     "legendFormat": "{{kubernetes_node_name}}/{{device}}"
    }
   ]
  },
  {
   "title": "Delete data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_deleted{datname=~\"$datname\",kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$instance\"} != 0",
     "legendFormat": "{{kubernetes_pod_name}}/{{datname}}"
    }
   ]
  },
  {
   "title": "Return data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_returned{datname=~\"$datname\",kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$instance\"} != 0",
     "legendFormat": "{{kubernetes_pod_name}}/{{datname}}"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_locks_count{datname=~\"$datname\",kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$instance\",mode=~\"$mode\"} != 0",
     "legendFormat": "{{kubernetes_pod_name}}/{{datname}} ({{mode}})"
    }
   ]
  },
  {
   "title": "Disk Use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_filesystem_free_bytes{kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\",fstype!~\"selinuxfs|autofs|rpc_pipefs|tmpfs\"} / node_filesystem_size_bytes{kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\",fstype!~\"selinuxfs|autofs|rpc_pipefs|tmpfs\"})",
     "legendFormat": "{{kubernetes_node_name}}:{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(rate(node_disk_read_time_seconds_total{device=~\"$device\",kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\"}[$interval]) / rate(node_disk_reads_completed_total{device=~\"$device\",kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\"}[$interval])) or (irate(node_disk_read_time_seconds_total{device=~\"$device\",kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\"}[$interval]) / irate(node_disk_reads_completed_total{device=~\"$device\",kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\"}[$interval]))",
     "legendFormat": "{{kubernetes_node_name}} Read {{device}}"
    },
    {
     "expr": "(rate(node_disk_write_time_seconds_total{device=~\"$device\",kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\"}[$interval]) / rate(node_disk_writes_completed_total{device=~\"$device\",kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\"}[$interval])) or (irate(node_disk_write_time_seconds_total{device=~\"$device\",kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\"}[$interval]) / irate(node_disk_write_completed_total{device=~\"$device\",kubernetes_cluster=~\"$kube\",kubernetes_node_name=~\"$host\"}[$interval]))",
     "legendFormat": "{{kubernetes_node_name}} Write {{device}}"
    }
   ]
  }
 ]
}