{
 "title": "Redis",
 "description": "Redis metrics overview.",
 "tags": [
  "database",
  "nosgbd",
  "redis"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(redis_up,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(redis_up{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(redis_up{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "instance",
    "label": "Pod Name",
    "query": "label_values(redis_up{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(redis_connected_clients{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 * (sum by (kubernetes_cluster,kubernetes_pod_name) (redis_memory_used_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$instance\"})) / on (kubernetes_cluster,kubernetes_pod_name) group_left() sum by (kubernetes_cluster,kubernetes_pod_name) (label_replace(container_spec_memory_limit_bytes{pod=~\".+redis.+\",container=\"\"},\"kubernetes_pod_name\",\"$1\",\"pod\",\"(.+)\")))"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(redis_commands_processed_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[1m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (irate(redis_keyspace_hits_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} hits"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (irate(redis_keyspace_misses_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} misses"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (redis_memory_used_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} used"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (redis_memory_max_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} max"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(redis_net_input_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} IN"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(redis_net_output_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} OUT"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,db)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{db}}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name) (redis_db_keys{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}) - sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name) (redis_db_keys_expiring{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} not expiring"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name) (redis_db_keys_expiring{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} expiring"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} evicted"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,cmd) (irate(redis_commands_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[1m])))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{cmd}}"
    }
   ]
  }
 ]
}