{
 "title": "Rocket.Chat",
 "description": "Rocket.Chat metrics overview.",
 "tags": [
  "application",
  "nodejs",
  "rocketchat"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(rocketchat_callbacks_sum{},kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(rocketchat_callbacks_sum{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(rocketchat_callbacks_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "pod",
    "label": "Pod Name",
    "query": "label_values(rocketchat_callbacks_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Users Online",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(rocketchat_users_online{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name))"
    }
   ]
  },
  {
   "title": "Users Away",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(rocketchat_users_away{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name))"
    }
   ]
  },
  {
   "title": "DDP Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(rocketchat_ddp_connected_users{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name))"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(rocketchat_users_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name))"
    }
   ]
  },
  {
   "title": "Total Rooms",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(rocketchat_rooms_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}) by (kubernretes_cluster,kubernetes_namespace,kubernetes_deployment_name))"
    }
   ]
  },
  {
   "title": "Total Messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(rocketchat_messages_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}) by (kubernretes_cluster,kubernetes_namespace,kubernetes_deployment_name))"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Metrics Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernretes_cluster,kubernetes_namespace,kubernetes_service_name) (increase(rocketchat_metrics_requests{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "Metrics Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernretes_cluster,kubernetes_namespace,kubernetes_service_name) (rocketchat_metrics_size{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  },
  { "title": "NodeJS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Active Handles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernretes_cluster,kubernetes_namespace,kubernetes_service_name) (nodejs_active_handles_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernretes_cluster,kubernetes_namespace,kubernetes_service_name) (nodejs_active_requests_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "Event loop lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernretes_cluster,kubernetes_namespace,kubernetes_service_name) (nodejs_eventloop_lag_seconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernretes_cluster,kubernetes_namespace,kubernetes_service_name) (nodejs_heap_size_used_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "Per pod heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernretes_cluster,kubernetes_namespace,kubernetes_pod_name) (nodejs_heap_size_used_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC - Seconds Running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(nodejs_gc_duration_seconds_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "DDP Rate Limiter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Limit by type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\",user_id!=\"null\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,limit_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kuberentes_pod_name}} {{limit_name}} (not null)"
    },
    {
     "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\",user_id=\"null\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,limit_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{limit_name}} null"
    }
   ]
  },
  {
   "title": "Limit by method",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\",user_id!=\"null\"}[5m])) by (type,name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}{{type}}: {{name}} not null"
    },
    {
     "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\",user_id=\"null\"}[5m])) by (type,name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}{{type}}: {{name}} null"
    }
   ]
  },
  {
   "title": "Limit by userId",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m])) by (user_id)",
     "legendFormat": "{{user_id}}"
    }
   ]
  },
  {
   "title": "Limit by connectionId",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\",user_id!=\"null\"}[5m])) by (connection_id)",
     "legendFormat": "{{connection_id}} (notn null)"
    },
    {
     "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\",user_id=\"null\"}[5m])) by (connection_id)",
     "legendFormat": "{{connection_id}} (null)"
    }
   ]
  },
  { "title": "RocketChat Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Messages Sent (5m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(rocketchat_message_sent{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Messages Sent Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name) (rocketchat_messages_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "Users Presence",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rocketchat_users_online{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Online"
    },
    {
     "expr": "avg(rocketchat_users_away{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Away"
    }
   ]
  },
  {
   "title": "Users & Sessions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rocketchat_ddp_connected_users{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Connected"
    },
    {
     "expr": "sum(rocketchat_ddp_sessions_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"} by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Total Sessions"
    },
    {
     "expr": "sum(rocketchat_ddp_sessions_auth{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"} by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Authenticated Sessions"
    }
   ]
  },
  {
   "title": "Oplog",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rocketchat_meteor_stream{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m])) by (stream,eventName)",
     "legendFormat": "{{stream}}/{{eventName}}"
    },
    {
     "expr": "sum(increase(rocketchat_meteor_streamer_broadcast{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m])) by (stream,eventName)",
     "legendFormat": "broadcast ({{stream}}/{{eventName}})"
    },
    {
     "expr": "sum(increase(rocketchat_oplog{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m])) by (collection,op)",
     "legendFormat": "{{collection}}/{{op}}"
    }
   ]
  },
  {
   "title": "Oplog Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketchat_oplog_queue{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Push Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketchat_push_queue{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Meteor Facts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rocketchat_meteor_facts{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,pkg,fact)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{pkg}} {{fact}}"
    }
   ]
  },
  {
   "title": "Total of Users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "max(rocketchat_users_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Users"
    }
   ]
  },
  {
   "title": "Total of Rooms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "max(rocketchat_rooms_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Rooms"
    }
   ]
  },
  {
   "title": "Notifications / Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rocketchat_notification_sent{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,notification_type)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{notification_type}}"
    }
   ]
  },
  { "title": "Methods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 } },
  {
   "title": "Meteor Methods Total Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rocketchat_meteor_methods{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,method) * sum(increase(rocketchat_meteor_methods_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,method)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{method}}"
    }
   ]
  },
  {
   "title": "Meteor Methods Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rocketchat_meteor_methods{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,method)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{method}}"
    }
   ]
  },
  {
   "title": "Meteor Methods Calls / Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rocketchat_meteor_methods_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,method)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{method}}"
    }
   ]
  },
  { "title": "Subscriptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 } },
  {
   "title": "Meteor Subscription Total Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rocketchat_meteor_subscriptions{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}) by (subscription) * sum(increase(rocketchat_meteor_subscriptions_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,subscription)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{subscription}}"
    }
   ]
  },
  {
   "title": "Meteor Subscription Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rocketchat_meteor_subscriptions{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,subscription)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{subscription}}"
    }
   ]
  },
  {
   "title": "Meteor Subscription Calls / Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rocketchat_meteor_subscriptions_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,subscription)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{subscription}}"
    }
   ]
  },
  { "title": "Callbacks & Hooks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 171 } },
  {
   "title": "Callbacks Total Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 172 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rocketchat_callbacks{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,callback) * sum(increase(rocketchat_callbacks_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,callback)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{callback}}"
    }
   ]
  },
  {
   "title": "Callbacks Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 180 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(rocketchat_callbacks{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,callback)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{callback}}"
    }
   ]
  },
  {
   "title": "Callbacks Calls / Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 180 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rocketchat_callbacks_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,callback)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{callback}}"
    },
    {
     "expr": "sum(rocketchat_callbacks_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,hook)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{hook}}"
    }
   ]
  },
  {
   "title": "Hooks Total Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 188 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rocketchat_hooks{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,hook) * sum(increase(rocketchat_hooks_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,hook)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{hook}}"
    }
   ]
  },
  {
   "title": "Hooks Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 196 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(rocketchat_hooks{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,hook)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{hook}}"
    }
   ]
  },
  {
   "title": "Hooks Calls / Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 196 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rocketchat_hooks_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,hook)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{hook}}"
    },
    {
     "expr": "sum(rocketchat_callbacks_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,hook)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{hook}}"
    }
   ]
  },
  { "title": "REST API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 204 } },
  {
   "title": "REST API Total Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 205 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rocketchat_rest_api{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,entrypoint) * sum(increase(rocketchat_rest_api_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,entrypoint)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{entrypoint}}"
    }
   ]
  },
  {
   "title": "REST API Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 212 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(rocketchat_rest_api{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,entrypoint)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{entrypoint}}"
    }
   ]
  },
  {
   "title": "REST API Calls / Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 212 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rocketchat_rest_api_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,entrypoint)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{entrypoint}}"
    }
   ]
  }
 ]
}