{
 "title": "s3bucket",
 "description": "S3 Buckets overview.",
 "tags": [
  "buckets",
  "s3",
  "storage"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(s3_endpoint_up,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(s3_endpoint_up{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(s3_endpoint_up{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "s3 Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(s3_endpoint_up{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "s3 Space Usage by Bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (bucketname) (s3_bucket_size{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"})",
     "legendFormat": "{{ kubernetes_namespace }}/{{ bucketname }}"
    }
   ]
  },
  {
   "title": "s3 Total Objects Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (s3_total_object_number{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "s3 Objects Count by Bucket",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (bucketname) (s3_bucket_object_number{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"})",
     "legendFormat": "{{ kubernetes_namespace }}/{{ bucketname }}"
    }
   ]
  },
  {
   "title": "s3 Total Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (s3_total_size{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"})"
    }
   ]
  }
 ]
}