{
 "title": "Thanos Store",
 "description": "Thanos Store overview.",
 "tags": [
  "application",
  "go",
  "monitoring",
  "prometheus",
  "thanos"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "5m,10m,30m,1h,6h,12h" },
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(thanos_status{component=\"store\"},kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(thanos_status{component=\"store\",kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "pod",
    "label": "Kubernetes Pod Name",
    "query": "label_values(thanos_status{component=\"store\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "gRPC (Unary)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of handled Unary gRPC requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",grpc_type=\"unary\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,grpc_method,grpc_code)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",grpc_type=\"unary\"}[$interval])) / sum(rate(grpc_server_started_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",grpc_type=\"unary\"}[$interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",grpc_type=\"unary\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,grpc_method,le)) * 1",
     "legendFormat": "P99 {{kubernetes_namespace}}/{{kubernetes_pod_name}} {{grpc_method}}"
    },
    {
     "expr": "sum(rate(grpc_server_handling_seconds_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",grpc_type=\"unary\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) * 1 / sum(rate(grpc_server_handling_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",grpc_type=\"unary\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "mean {{kubernetes_namespace}}/{{kubernetes_pod_name}} {{grpc_method}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_server_handling_seconds_bucket{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",grpc_type=\"unary\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,grpc_method,le)) * 1",
     "legendFormat": "P50 {{kubernetes_namespace}}/{{kubernetes_pod_name}} {{grpc_method}}"
    }
   ]
  },
  { "title": "gRPC (Stream)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of handled Streamed gRPC requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",grpc_type=\"server_stream\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,grpc_method, grpc_code)",
     "legendFormat": "{{jkubernetes_namespace}}/{{kubernetes_pod_name}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",grpc_type=\"server_stream\"}[$interval])) / sum(rate(grpc_server_started_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",grpc_type=\"server_stream\"}[$interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",grpc_type=\"server_stream\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,grpc_method,le)) * 1",
     "legendFormat": "P99 {{kubernetes_namespace}}/{{kubernetes_pod_name}} {{grpc_method}}"
    },
    {
     "expr": "sum(rate(grpc_server_handling_seconds_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",grpc_type=\"server_stream\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) * 1 / sum(rate(grpc_server_handling_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",grpc_type=\"server_stream\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "mean {{kubernetes_namespace}}/{{kubernetes_pod_name}} {{grpc_method}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_server_handling_seconds_bucket{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",grpc_type=\"server_stream\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,grpc_method,le)) * 1",
     "legendFormat": "P50 {{kubernetes_namespace}}/{{kubernetes_pod_name}} {{grpc_method}}"
    }
   ]
  },
  { "title": "Bucket Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of execution for operations against the bucket.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_objstore_bucket_operations_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,operation)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{operation}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of executed operations against the bucket.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,operation) (rate(thanos_objstore_bucket_operation_failures_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) / sum by (kubernetes_cluster,kubernetes_namaespace,kubernetes_pod_name,operation) (rate(thanos_objstore_bucket_operations_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{operation}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to execute operations against the bucket, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(thanos_objstore_bucket_operation_duration_seconds_bucket{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namaespace,kubernetes_pod_name,operation,le)) * 1",
     "legendFormat": "P99 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(thanos_objstore_bucket_operation_duration_seconds_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namaespace,kubernetes_pod_name,operation) * 1 / sum(rate(thanos_objstore_bucket_operation_duration_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namaespace,kubernetes_pod_name,operation)",
     "legendFormat": "mean {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(thanos_objstore_bucket_operation_duration_seconds_bucket{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namaespace,kubernetes_pod_name,operation,le)) * 1",
     "legendFormat": "P50 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Block Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Block Load Rate",
   "type": "graph",
   "description": "Shows rate of block loads from the bucket.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_bucket_store_block_loads_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "block loads"
    }
   ]
  },
  {
   "title": "Block Load Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of block loads from the bucket.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_bucket_store_block_load_failures_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) / sum(rate(thanos_bucket_store_block_loads_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Block Drop Rate",
   "type": "graph",
   "description": "Shows rate of block drops.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_bucket_store_block_drops_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "Block drops"
    }
   ]
  },
  {
   "title": "Block Drop Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of block drops.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_bucket_store_block_drop_failures_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) / sum(rate(thanos_bucket_store_block_drops_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  { "title": "Cache Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Requests",
   "type": "graph",
   "description": "Show rate of cache requests.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_store_index_cache_requests_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,item_type)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{item_type}}"
    }
   ]
  },
  {
   "title": "Hits",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of cache hits.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_store_index_cache_hits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,item_type)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{item_type}}"
    }
   ]
  },
  {
   "title": "Added",
   "type": "graph",
   "description": "Show rate of added items to cache.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_store_index_cache_items_added_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,item_type)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{item_type}}"
    }
   ]
  },
  {
   "title": "Evicted",
   "type": "graph",
   "description": "Show rate of evicted items from cache.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_store_index_cache_items_evicted_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,item_type)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{item_type}}"
    }
   ]
  },
  { "title": "Store Sent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Chunk Size",
   "type": "graph",
   "description": "Shows size of chunks that have sent to the bucket.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(thanos_bucket_store_sent_chunk_size_bytes_bucket{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,le))",
     "legendFormat": "P99 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_sent_chunk_size_bytes_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) / sum(rate(thanos_bucket_store_sent_chunk_size_bytes_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "mean {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(thanos_bucket_store_sent_chunk_size_bytes_bucket{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,le))",
     "legendFormat": "P50 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Series Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Block queried",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thanos_bucket_store_series_blocks_queried{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",quantile=\"0.99\"}",
     "legendFormat": "P99 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_series_blocks_queried_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) / sum(rate(thanos_bucket_store_series_blocks_queried_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "mean {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "thanos_bucket_store_series_blocks_queried{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",quantile=\"0.50\"}",
     "legendFormat": "P50 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Data Fetched",
   "type": "graph",
   "description": "Show the size of data fetched",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "thanos_bucket_store_series_data_fetched{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",quantile=\"0.99\"}",
     "legendFormat": "P99 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_series_data_fetched_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) / sum(rate(thanos_bucket_store_series_data_fetched_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "mean {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "thanos_bucket_store_series_data_fetched{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",quantile=\"0.50\"}",
     "legendFormat": "P50 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Result series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thanos_bucket_store_series_result_series{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",quantile=\"0.99\"}",
     "legendFormat": "P99 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_series_result_series_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) / sum(rate(thanos_bucket_store_series_result_series_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "mean {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "thanos_bucket_store_series_result_series{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\",quantile=\"0.50\"}",
     "legendFormat": "P50 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Series Operation Durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Get All",
   "type": "graph",
   "description": "Shows how long has it taken to get all series.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(thanos_bucket_store_series_get_all_duration_seconds_bucket{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,le)) * 1",
     "legendFormat": "P99 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_series_get_all_duration_seconds_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) * 1 / sum(rate(thanos_bucket_store_series_get_all_duration_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "mean {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(thanos_bucket_store_series_get_all_duration_seconds_bucket{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,le)) * 1",
     "legendFormat": "P50 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Merge",
   "type": "graph",
   "description": "Shows how long has it taken to merge series.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(thanos_bucket_store_series_merge_duration_seconds_bucket{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,le)) * 1",
     "legendFormat": "P99 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_series_merge_duration_seconds_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) * 1 / sum(rate(thanos_bucket_store_series_merge_duration_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "mean {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(thanos_bucket_store_series_merge_duration_seconds_bucket{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,le)) * 1",
     "legendFormat": "P50 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Gate",
   "type": "graph",
   "description": "Shows how long has it taken for a series to wait at the gate.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(thanos_bucket_store_series_gate_duration_seconds_bucket{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,le)) * 1",
     "legendFormat": "P99 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_series_gate_duration_seconds_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) * 1 / sum(rate(thanos_bucket_store_series_gate_duration_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "mean {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(thanos_bucket_store_series_gate_duration_seconds_bucket{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,le)) * 1",
     "legendFormat": "P50 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "alloc all {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "alloc heap {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])",
     "legendFormat": "alloc rate all {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(go_memstats_heap_alloc_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}[$interval])",
     "legendFormat": "alloc rate heap {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "inuse stack {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "inuse heap {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{quantile}} {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}