{
 "title": "Thanos Query",
 "description": "Thanos Query overview.",
 "tags": [
  "application",
  "go",
  "monitoring",
  "prometheus",
  "thanos"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "5m,10m,30m,1h,6h,12h" },
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(thanos_query_duplicated_store_addresses_total,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(thanos_query_duplicated_store_addresses_total{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "pod",
    "label": "Kubernetes Pod",
    "query": "label_values(thanos_query_duplicated_store_addresses_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "Instant Query API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of requests against /query for the given time.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(http_requests_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",handler=\"query\"}[$interval]),\"status_code\", \"${1}xx\", \"code\", \"([0-9])..\")) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,handler,status_code)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{handler}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the the total number of handled requests against /query.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",handler=\"query\",code=~\"5..\"}[$interval])) / sum(rate(http_requests_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",handler=\"query\"}[$interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",handler=\"query\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,le)) * 1",
     "legendFormat": "P99 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",handler=\"query\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) * 1 / sum(rate(http_request_duration_seconds_count{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",handler=\"query\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "mean {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",handler=\"query\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,le)) * 1",
     "legendFormat": "P50 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Range Query API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of requests against /query_range for the given time range.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(http_requests_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",handler=\"query_range\"}[$interval]),\"status_code\", \"${1}xx\", \"code\", \"([0-9])..\")) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,handler,status_code)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{handler}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the the total number of handled requests against /query_range.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",handler=\"query_range\",code=~\"5..\"}[$interval])) / sum(rate(http_requests_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",handler=\"query_range\"}[$interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",handler=\"query_range\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,le)) * 1",
     "legendFormat": "P99 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",handler=\"query_range\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) * 1 / sum(rate(http_request_duration_seconds_count{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",handler=\"query_range\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "mean {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",handler=\"query_range\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,le)) * 1",
     "legendFormat": "P50 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "gRPC (Unary)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of handled Unary gRPC requests from other queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_client_handled_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",grpc_type=\"unary\"}[$interval])) by (kubernetes_cluster,kubernetes_pod_name,kubernetes_namespace,grpc_method,grpc_code)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the the total number of handled requests from other queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_client_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",grpc_type=\"unary\"}[$interval])) / sum(rate(grpc_client_started_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",grpc_type=\"unary\"}[$interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests from other queriers, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_client_handling_seconds_bucket{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",grpc_type=\"unary\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,grpc_method,le)) * 1",
     "legendFormat": "P99 {{kubernetes_namespace}}/{{kubernetes_pod_name}} {{grpc_method}}"
    },
    {
     "expr": "sum(rate(grpc_client_handling_seconds_sum{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",grpc_type=\"unary\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) * 1 / sum(rate(grpc_client_handling_seconds_count{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",grpc_type=\"unary\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "mean {{kubernetes_namespace}}/{{kubernetes_pod_name}} {{grpc_method}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_client_handling_seconds_bucket{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",grpc_type=\"unary\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,grpc_method,le)) * 1",
     "legendFormat": "P50 {{kubernetes_namespace}}/{{kubernetes_pod_name}} {{grpc_method}}"
    }
   ]
  },
  { "title": "gRPC (Stream)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of handled Streamed gRPC requests from other queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_client_handled_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",grpc_type=\"server_stream\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,grpc_method,grpc_code)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the the total number of handled requests from other queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_client_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",grpc_type=\"server_stream\"}[$interval])) / sum(rate(grpc_client_started_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",grpc_type=\"server_stream\"}[$interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests from other queriers, in quantiles",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_client_handling_seconds_bucket{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",grpc_type=\"server_stream\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,grpc_method,le)) * 1",
     "legendFormat": "P99 {{kubernetes_namespace}}/{{kubernetes_pod_name}} {{grpc_method}}"
    },
    {
     "expr": "sum(rate(grpc_client_handling_seconds_sum{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",grpc_type=\"server_stream\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) * 1 / sum(rate(grpc_client_handling_seconds_count{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",grpc_type=\"server_stream\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "mean {{kubernetes_namespace}}/{{kubernetes_pod_name}} {{grpc_method}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_client_handling_seconds_bucket{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\",grpc_type=\"server_stream\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,grpc_method,le)) * 1",
     "legendFormat": "P50 {{kubernetes_namespace}}/{{kubernetes_pod_name}} {{grpc_method}}"
    }
   ]
  },
  { "title": "DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of DNS lookups to discover stores.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_query_store_apis_dns_lookups_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "lookups {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of failures compared to the the total number of executed DNS lookups.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_query_store_apis_dns_failures_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) / sum(rate(thanos_query_store_apis_dns_lookups_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "alloc all {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "alloc heap {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])",
     "legendFormat": "alloc rate all {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(go_memstats_heap_alloc_bytes{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])",
     "legendFormat": "alloc rate heap {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "inuse stack {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "inuse heap {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{quantile}} {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}