{
 "title": "Thanos Compact",
 "description": "Thanos Compact overview.",
 "tags": [
  "application",
  "go",
  "monitoring",
  "prometheus",
  "thanos"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "5m,10m,30m,1h,6h,12h" },
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(thanos_compact_garbage_collection_total,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(thanos_compact_garbage_collection_total{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "pod",
    "label": "Kubernetes Pod Name",
    "query": "label_values(thanos_compact_garbage_collection_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "Group Compaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of execution for compactions against blocks that are stored in the bucket by compaction group.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_compact_group_compactions_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,group)",
     "legendFormat": "compaction {{kubernetes_namespace}}/{{kubernetes_pod_name}} {{group}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of executed compactions against blocks that are stored in the bucket.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_compact_group_compactions_failures_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) / sum(rate(thanos_compact_group_compactions_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  { "title": "Downsample", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of execution for downsampling against blocks that are stored in the bucket by compaction group.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_compact_downsample_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,group)",
     "legendFormat": "downsample {{kubernetes_namespace}}/{{kubernetes_pod_name}} {{group}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of executed downsampling against blocks that are stored in the bucket.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_compact_downsample_failed_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) / sum(rate(thanos_compact_downsample_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of execution for removals of blocks if their data is available as part of a block with a higher compaction level.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_compact_garbage_collection_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "garbage collection {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of executed garbage collections.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_compact_garbage_collection_failures_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) / sum(rate(thanos_compact_garbage_collection_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to execute garbage collection in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(thanos_compact_garbage_collection_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,le)) * 1",
     "legendFormat": "P99 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(thanos_compact_garbage_collection_duration_seconds_sum{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) * 1 / sum(rate(thanos_compact_garbage_collection_duration_seconds_count{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "mean {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(thanos_compact_garbage_collection_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,le)) * 1",
     "legendFormat": "P50 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Sync Meta", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of execution for all meta files from blocks in the bucket into the memory.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_blocks_meta_syncs_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "sync {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of executed meta file sync.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_blocks_meta_sync_failures_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) / sum(rate(thanos_blocks_meta_syncs_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to execute meta file sync, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(thanos_blocks_meta_sync_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,le)) * 1",
     "legendFormat": "P99 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(thanos_blocks_meta_sync_duration_seconds_sum{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) * 1 / sum(rate(thanos_blocks_meta_sync_duration_seconds_count{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "mean {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(thanos_blocks_meta_sync_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,le)) * 1",
     "legendFormat": "P50 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Object Store Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of execution for operations against the bucket.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_objstore_bucket_operations_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,operation)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{operation}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of executed operations against the bucket.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_objstore_bucket_operation_failures_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) / sum(rate(thanos_objstore_bucket_operations_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to execute operations against the bucket, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(thanos_objstore_bucket_operation_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,le)) * 1",
     "legendFormat": "P99 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(thanos_objstore_bucket_operation_duration_seconds_sum{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) * 1 / sum(rate(thanos_objstore_bucket_operation_duration_seconds_count{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "mean {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(thanos_objstore_bucket_operation_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,le)) * 1",
     "legendFormat": "P50 {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "alloc all {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "alloc heap {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])",
     "legendFormat": "alloc rate all {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(go_memstats_heap_alloc_bytes{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}[$interval])",
     "legendFormat": "alloc rate heap {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "inuse stack {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "inuse heap {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{kubernetes_namespace=~\"$namespace\",kubernetes_cluster=~\"$cluster\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{quantile}} {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}